# Tensor Decomposition Experiments
*Thomas Dooms applicant task - extended experiment notebook*

This notebook turns the provided tensor-decomposition skeleton into a small experimental study. The goal is not merely to reconstruct the bilinear interaction tensor, but to find shared components that are compact, faithful, stable, and easy to name as digit strokes or counter-strokes.

## What We Are Testing

The trained bilinear MNIST model computes logits from a third-order interaction tensor:

$$\text{logit}_c(x) = \sum_{i,j} B_{c,i,j}\,x_i\,x_j$$

The tutorial baseline fits a shared CP-style factorization:

$$B_{c,i,j} \approx \sum_r L_{i,r} R_{j,r} D_{c,r}$$

That already shares features across classes, but pure reconstruction pressure can still produce noisy or superposed components. Below we compare several priors:

- the provided sparse baseline
- symmetric factors: $L=R$
- sparse and smooth image-domain factors
- direct positive/negative evidence splits
- nonnegative stroke factors
- eigenvector-seeded shared dictionaries
- multi-seed consensus components

The core question is whether a small loss in reconstruction quality buys a large gain in interpretability.

## Setup

In [1]:
%load_ext autoreload
%autoreload 2

import math
import os
import random
from dataclasses import dataclass, asdict
from pathlib import Path

import torch
import torch.nn as nn
import torch.nn.functional as F
import plotly.express as px
from plotly.subplots import make_subplots
from tqdm import tqdm

from image import Model, MNIST
from image.sparse import Model as Sparse
from kornia.augmentation import RandomGaussianNoise
from einops import einsum

try:
    import pandas as pd
except Exception:
    pd = None

FIG_DIR = Path("figures")
FIG_DIR.mkdir(exist_ok=True)
EXPORT_FIGURES = True

if torch.cuda.is_available():
    device = "cuda:0"
elif hasattr(torch.backends, "mps") and torch.backends.mps.is_available():
    device = "mps"
else:
    device = "cpu"

RUN_PROFILE = os.environ.get("RUN_PROFILE", "balanced")
if RUN_PROFILE == "full":
    MODEL_EPOCHS = 20
    BASE_RANK = 64
    LARGE_RANK = 96
    BASELINE_STEPS = 200
    VARIANT_STEP_SCALE = 1.0
    CONSENSUS_STEPS = 300
else:
    MODEL_EPOCHS = 4
    BASE_RANK = 32
    LARGE_RANK = 48
    BASELINE_STEPS = 80
    VARIANT_STEP_SCALE = 0.22
    CONSENSUS_STEPS = 80

torch.set_float32_matmul_precision("high") if hasattr(torch, "set_float32_matmul_precision") else None

def set_seed(seed=0):
    random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)

set_seed(0)
train, test = MNIST(train=True, device=device), MNIST(train=False, device=device)
device

'mps'

In [2]:
def save_fig(fig, name):
    """Save interactive HTML and, when kaleido is available, a README-friendly PNG."""
    if not EXPORT_FIGURES:
        return fig
    html_path = FIG_DIR / f"{name}.html"
    png_path = FIG_DIR / f"{name}.png"
    fig.write_html(str(html_path), include_plotlyjs="cdn")
    try:
        fig.write_image(str(png_path), scale=2)
    except Exception as exc:
        print(f"Saved {html_path}; PNG export skipped ({type(exc).__name__}: {exc})")
    return fig


def show_table(rows, sort_by=None):
    if pd is not None:
        df = pd.DataFrame(rows)
        if sort_by is not None and sort_by in df:
            df = df.sort_values(sort_by, ascending=False)
        display(df)
        return df
    for row in rows:
        print(row)
    return rows


def make_optimizer(params, lr=2e-2, momentum=0.95, weight_decay=0.0):
    # Muon was used in the skeleton. Fall back cleanly for environments with older torch.
    if hasattr(torch.optim, "Muon") and momentum is not None:
        return torch.optim.Muon(params, lr=lr, momentum=momentum, weight_decay=weight_decay)
    return torch.optim.AdamW(params, lr=lr, weight_decay=weight_decay)

## Train The Original Bilinear Model

In [3]:
set_seed(0)
model = Model.from_config(epochs=MODEL_EPOCHS).to(device)
metrics = model.fit(train, test, RandomGaussianNoise(std=0.4).to(device))

with torch.no_grad():
    original_acc = (model(test.x).argmax(-1) == test.y).float().mean().item()
original_acc

epoch 01/4 loss=0.4234 acc=0.9587

epoch 02/4 loss=0.2086 acc=0.9647

epoch 03/4 loss=0.1866 acc=0.9672

epoch 04/4 loss=0.1648 acc=0.9740

0.9739999771118164

## Build The Interaction Tensor

The decomposition variants below operate in pixel/input space, so the original bilinear tensor includes the image embedding matrix. This makes each learned component directly viewable as a `28 x 28` pattern.

In [4]:
@torch.no_grad()
def interaction_tensor(model):
    """Return the symmetrized input-space tensor B[c, pix_i, pix_j]."""
    l, r = model.w_lr[0].unbind()
    b = einsum(
        model.w_u,
        l,
        r,
        model.w_e,
        model.w_e,
        "cls out, out hid1, out hid2, hid1 pix1, hid2 pix2 -> cls pix1 pix2",
    )
    return 0.5 * (b + b.mT)

B = interaction_tensor(model).detach()
B_norm = B.norm()
B.shape, B_norm.item()

(torch.Size([10, 784, 784]), 10.269742965698242)

## Evaluation Helpers

In [5]:
def cosine_to_target(approx, target=B):
    return F.cosine_similarity(approx.flatten(), target.flatten(), dim=0)


def normalize_columns(x, eps=1e-8):
    return x / x.norm(dim=0, keepdim=True).clamp_min(eps)


def gini_1d(x, eps=1e-8):
    x = x.detach().abs().flatten()
    if x.numel() == 0 or x.sum() < eps:
        return torch.tensor(0.0, device=x.device)
    x = x.sort().values
    n = x.numel()
    idx = torch.arange(1, n + 1, device=x.device, dtype=x.dtype)
    return ((2 * idx - n - 1) * x).sum() / (n * x.sum().clamp_min(eps))


def mean_gini(patterns):
    cols = patterns.T if patterns.shape[0] == 784 else patterns
    return torch.stack([gini_1d(col) for col in cols]).mean()


def total_variation(patterns):
    imgs = patterns.T.reshape(-1, 1, 28, 28)
    dy = (imgs[:, :, 1:, :] - imgs[:, :, :-1, :]).abs().mean()
    dx = (imgs[:, :, :, 1:] - imgs[:, :, :, :-1]).abs().mean()
    return dx + dy


def patch_locality(patterns, patch=7, eps=1e-8):
    """Mean fraction of each component's squared mass captured by its best local patch."""
    imgs = patterns.T.reshape(-1, 1, 28, 28)
    energy = imgs.square()
    pooled = F.avg_pool2d(energy, kernel_size=patch, stride=1) * (patch * patch)
    best = pooled.flatten(1).max(dim=1).values
    total = energy.flatten(1).sum(dim=1).clamp_min(eps)
    return (best / total).mean()


def class_selectivity(down, eps=1e-8):
    """1 - normalized entropy of abs class weights. Higher means fewer classes per component."""
    p = down.detach().abs()
    p = p / p.sum(dim=0, keepdim=True).clamp_min(eps)
    entropy = -(p * (p + eps).log()).sum(dim=0) / math.log(p.shape[0])
    return 1 - entropy.mean()


def metric_dict(name, factor_model, target=B):
    with torch.no_grad():
        approx = factor_model.tensor()
        logits = factor_model(test.x)
        plus, minus, down, sigma = factor_model.decompose()
        patterns = torch.cat([plus, minus], dim=1)
        return {
            "name": name,
            "similarity": cosine_to_target(approx, target).item(),
            "test_acc": (logits.argmax(-1) == test.y).float().mean().item(),
            "pattern_gini": mean_gini(patterns).item(),
            "locality_7x7": patch_locality(patterns).item(),
            "class_selectivity": class_selectivity(down).item(),
            "top_sigma_frac": (sigma[:8].sum() / sigma.sum().clamp_min(1e-8)).item(),
        }


def builtin_sparse_metrics(name, sparse, original_model=model):
    with torch.no_grad():
        plus, minus, down, sigma = sparse.decompose()
        patterns = torch.cat([plus, minus], dim=1)
        return {
            "name": name,
            "similarity": sparse.similarity(original_model).item(),
            "test_acc": (sparse(test.x).argmax(-1) == test.y).float().mean().item(),
            "pattern_gini": mean_gini(patterns).item(),
            "locality_7x7": patch_locality(patterns).item(),
            "class_selectivity": class_selectivity(down).item(),
            "top_sigma_frac": (sigma[:8].sum() / sigma.sum().clamp_min(1e-8)).item(),
        }

## Plotting Helpers

In [6]:
def component_figure(plus, minus, down, sigma=None, k=8, title="components"):
    plus, minus, down = plus.detach().cpu(), minus.detach().cpu(), down.detach().cpu()
    k = min(k, plus.shape[1])
    fig = make_subplots(
        rows=3,
        cols=k,
        row_titles=["positive", "negative", "logits"],
        vertical_spacing=0.08,
        horizontal_spacing=0.02,
    )
    for i in range(k):
        params = dict(showscale=False, colorscale="RdBu", zmid=0)
        fig.add_heatmap(z=plus[:, i].view(28, 28).flip(0), **params, row=1, col=i + 1)
        fig.add_heatmap(z=minus[:, i].view(28, 28).flip(0), **params, row=2, col=i + 1)
        colors = ["#666666"] * 10
        top_cls = int(down[:, i].abs().argmax())
        colors[top_cls] = "#c43c39"
        fig.add_bar(y=down[:, i], marker_color=colors, showlegend=False, row=3, col=i + 1)
    fig.update_xaxes(visible=False).update_yaxes(visible=False)
    fig.update_layout(
        width=max(900, k * 125),
        height=420,
        title=title,
        margin=dict(l=50, r=5, b=5, t=45),
        template="plotly_white",
    )
    return fig


def plot_factor_components(factor_model, name, k=8):
    plus, minus, down, sigma = factor_model.decompose()
    fig = component_figure(plus, minus, down, sigma, k=k, title=name)
    return save_fig(fig, f"components_{name.replace(' ', '_').lower()}")


def plot_sigma(sigma, name):
    fig = px.bar(
        sigma.detach().cpu(),
        template="plotly_white",
        labels=dict(index="component", value="sigma"),
        title=f"Component spectrum: {name}",
    )
    return save_fig(fig, f"sigma_{name.replace(' ', '_').lower()}")

def component_strengths(factor_model):
    if hasattr(factor_model, "component_strengths"):
        try:
            return factor_model.component_strengths()
        except NotImplementedError:
            pass
    return factor_model.decompose()[-1]

## Baseline: Provided Sparse Model

In [7]:
def fit_builtin_sparse(rank=64, steps=200, lr=0.02, seed=0):
    set_seed(seed)
    sparse = Sparse.from_config(rank=rank).to(device)
    optimizer = make_optimizer(sparse.parameters(), lr=lr, momentum=0.95)
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=steps)

    torch.set_grad_enabled(True)
    for _ in (pbar := tqdm(range(steps), desc="builtin sparse")):
        loss = 1 - sparse.similarity(model)
        optimizer.zero_grad(set_to_none=True)
        loss.backward()
        optimizer.step()
        scheduler.step()
        pbar.set_description(f"builtin sparse loss={loss.item():.4f}")
    torch.set_grad_enabled(False)
    return sparse

builtin = fit_builtin_sparse(rank=BASE_RANK, steps=BASELINE_STEPS, seed=0)
builtin_row = builtin_sparse_metrics(f"provided Sparse r{BASE_RANK}", builtin)
show_table([builtin_row])

builtin sparse:   0%|          | 0/80 [00:00<?, ?it/s]

builtin sparse loss=0.9999:   0%|          | 0/80 [00:00<?, ?it/s]

builtin sparse loss=0.9727:   0%|          | 0/80 [00:00<?, ?it/s]

builtin sparse loss=0.9727:   2%|▎         | 2/80 [00:00<00:04, 16.22it/s]

builtin sparse loss=0.9219:   2%|▎         | 2/80 [00:00<00:04, 16.22it/s]

builtin sparse loss=0.8413:   2%|▎         | 2/80 [00:00<00:04, 16.22it/s]

builtin sparse loss=0.7401:   2%|▎         | 2/80 [00:00<00:04, 16.22it/s]

builtin sparse loss=0.6344:   2%|▎         | 2/80 [00:00<00:04, 16.22it/s]

builtin sparse loss=0.6344:   8%|▊         | 6/80 [00:00<00:02, 26.49it/s]

builtin sparse loss=0.5365:   8%|▊         | 6/80 [00:00<00:02, 26.49it/s]

builtin sparse loss=0.4538:   8%|▊         | 6/80 [00:00<00:02, 26.49it/s]

builtin sparse loss=0.3870:   8%|▊         | 6/80 [00:00<00:02, 26.49it/s]

builtin sparse loss=0.3365:   8%|▊         | 6/80 [00:00<00:02, 26.49it/s]

builtin sparse loss=0.3365:  12%|█▎        | 10/80 [00:00<00:02, 30.33it/s]

builtin sparse loss=0.3011:  12%|█▎        | 10/80 [00:00<00:02, 30.33it/s]

builtin sparse loss=0.2777:  12%|█▎        | 10/80 [00:00<00:02, 30.33it/s]

builtin sparse loss=0.2622:  12%|█▎        | 10/80 [00:00<00:02, 30.33it/s]

builtin sparse loss=0.2515:  12%|█▎        | 10/80 [00:00<00:02, 30.33it/s]

builtin sparse loss=0.2515:  18%|█▊        | 14/80 [00:00<00:02, 31.70it/s]

builtin sparse loss=0.2434:  18%|█▊        | 14/80 [00:00<00:02, 31.70it/s]

builtin sparse loss=0.2371:  18%|█▊        | 14/80 [00:00<00:02, 31.70it/s]

builtin sparse loss=0.2317:  18%|█▊        | 14/80 [00:00<00:02, 31.70it/s]

builtin sparse loss=0.2272:  18%|█▊        | 14/80 [00:00<00:02, 31.70it/s]

builtin sparse loss=0.2272:  22%|██▎       | 18/80 [00:00<00:01, 32.21it/s]

builtin sparse loss=0.2228:  22%|██▎       | 18/80 [00:00<00:01, 32.21it/s]

builtin sparse loss=0.2186:  22%|██▎       | 18/80 [00:00<00:01, 32.21it/s]

builtin sparse loss=0.2148:  22%|██▎       | 18/80 [00:00<00:01, 32.21it/s]

builtin sparse loss=0.2111:  22%|██▎       | 18/80 [00:00<00:01, 32.21it/s]

builtin sparse loss=0.2111:  28%|██▊       | 22/80 [00:00<00:01, 32.41it/s]

builtin sparse loss=0.2077:  28%|██▊       | 22/80 [00:00<00:01, 32.41it/s]

builtin sparse loss=0.2041:  28%|██▊       | 22/80 [00:00<00:01, 32.41it/s]

builtin sparse loss=0.2005:  28%|██▊       | 22/80 [00:00<00:01, 32.41it/s]

builtin sparse loss=0.1970:  28%|██▊       | 22/80 [00:00<00:01, 32.41it/s]

builtin sparse loss=0.1970:  32%|███▎      | 26/80 [00:00<00:01, 32.73it/s]

builtin sparse loss=0.1937:  32%|███▎      | 26/80 [00:00<00:01, 32.73it/s]

builtin sparse loss=0.1904:  32%|███▎      | 26/80 [00:00<00:01, 32.73it/s]

builtin sparse loss=0.1874:  32%|███▎      | 26/80 [00:00<00:01, 32.73it/s]

builtin sparse loss=0.1844:  32%|███▎      | 26/80 [00:00<00:01, 32.73it/s]

builtin sparse loss=0.1844:  38%|███▊      | 30/80 [00:00<00:01, 32.83it/s]

builtin sparse loss=0.1817:  38%|███▊      | 30/80 [00:00<00:01, 32.83it/s]

builtin sparse loss=0.1791:  38%|███▊      | 30/80 [00:01<00:01, 32.83it/s]

builtin sparse loss=0.1766:  38%|███▊      | 30/80 [00:01<00:01, 32.83it/s]

builtin sparse loss=0.1743:  38%|███▊      | 30/80 [00:01<00:01, 32.83it/s]

builtin sparse loss=0.1743:  42%|████▎     | 34/80 [00:01<00:01, 32.93it/s]

builtin sparse loss=0.1721:  42%|████▎     | 34/80 [00:01<00:01, 32.93it/s]

builtin sparse loss=0.1699:  42%|████▎     | 34/80 [00:01<00:01, 32.93it/s]

builtin sparse loss=0.1680:  42%|████▎     | 34/80 [00:01<00:01, 32.93it/s]

builtin sparse loss=0.1661:  42%|████▎     | 34/80 [00:01<00:01, 32.93it/s]

builtin sparse loss=0.1661:  48%|████▊     | 38/80 [00:01<00:01, 33.47it/s]

builtin sparse loss=0.1643:  48%|████▊     | 38/80 [00:01<00:01, 33.47it/s]

builtin sparse loss=0.1626:  48%|████▊     | 38/80 [00:01<00:01, 33.47it/s]

builtin sparse loss=0.1611:  48%|████▊     | 38/80 [00:01<00:01, 33.47it/s]

builtin sparse loss=0.1596:  48%|████▊     | 38/80 [00:01<00:01, 33.47it/s]

builtin sparse loss=0.1596:  52%|█████▎    | 42/80 [00:01<00:01, 33.79it/s]

builtin sparse loss=0.1583:  52%|█████▎    | 42/80 [00:01<00:01, 33.79it/s]

builtin sparse loss=0.1570:  52%|█████▎    | 42/80 [00:01<00:01, 33.79it/s]

builtin sparse loss=0.1559:  52%|█████▎    | 42/80 [00:01<00:01, 33.79it/s]

builtin sparse loss=0.1547:  52%|█████▎    | 42/80 [00:01<00:01, 33.79it/s]

builtin sparse loss=0.1547:  57%|█████▊    | 46/80 [00:01<00:01, 33.57it/s]

builtin sparse loss=0.1537:  57%|█████▊    | 46/80 [00:01<00:01, 33.57it/s]

builtin sparse loss=0.1527:  57%|█████▊    | 46/80 [00:01<00:01, 33.57it/s]

builtin sparse loss=0.1518:  57%|█████▊    | 46/80 [00:01<00:01, 33.57it/s]

builtin sparse loss=0.1509:  57%|█████▊    | 46/80 [00:01<00:01, 33.57it/s]

builtin sparse loss=0.1509:  62%|██████▎   | 50/80 [00:01<00:00, 33.27it/s]

builtin sparse loss=0.1500:  62%|██████▎   | 50/80 [00:01<00:00, 33.27it/s]

builtin sparse loss=0.1492:  62%|██████▎   | 50/80 [00:01<00:00, 33.27it/s]

builtin sparse loss=0.1485:  62%|██████▎   | 50/80 [00:01<00:00, 33.27it/s]

builtin sparse loss=0.1478:  62%|██████▎   | 50/80 [00:01<00:00, 33.27it/s]

builtin sparse loss=0.1478:  68%|██████▊   | 54/80 [00:01<00:00, 33.07it/s]

builtin sparse loss=0.1472:  68%|██████▊   | 54/80 [00:01<00:00, 33.07it/s]

builtin sparse loss=0.1466:  68%|██████▊   | 54/80 [00:01<00:00, 33.07it/s]

builtin sparse loss=0.1460:  68%|██████▊   | 54/80 [00:01<00:00, 33.07it/s]

builtin sparse loss=0.1455:  68%|██████▊   | 54/80 [00:01<00:00, 33.07it/s]

builtin sparse loss=0.1455:  72%|███████▎  | 58/80 [00:01<00:00, 32.93it/s]

builtin sparse loss=0.1450:  72%|███████▎  | 58/80 [00:01<00:00, 32.93it/s]

builtin sparse loss=0.1445:  72%|███████▎  | 58/80 [00:01<00:00, 32.93it/s]

builtin sparse loss=0.1441:  72%|███████▎  | 58/80 [00:01<00:00, 32.93it/s]

builtin sparse loss=0.1437:  72%|███████▎  | 58/80 [00:01<00:00, 32.93it/s]

builtin sparse loss=0.1437:  78%|███████▊  | 62/80 [00:01<00:00, 32.82it/s]

builtin sparse loss=0.1434:  78%|███████▊  | 62/80 [00:01<00:00, 32.82it/s]

builtin sparse loss=0.1431:  78%|███████▊  | 62/80 [00:01<00:00, 32.82it/s]

builtin sparse loss=0.1428:  78%|███████▊  | 62/80 [00:02<00:00, 32.82it/s]

builtin sparse loss=0.1425:  78%|███████▊  | 62/80 [00:02<00:00, 32.82it/s]

builtin sparse loss=0.1425:  82%|████████▎ | 66/80 [00:02<00:00, 32.72it/s]

builtin sparse loss=0.1422:  82%|████████▎ | 66/80 [00:02<00:00, 32.72it/s]

builtin sparse loss=0.1420:  82%|████████▎ | 66/80 [00:02<00:00, 32.72it/s]

builtin sparse loss=0.1418:  82%|████████▎ | 66/80 [00:02<00:00, 32.72it/s]

builtin sparse loss=0.1417:  82%|████████▎ | 66/80 [00:02<00:00, 32.72it/s]

builtin sparse loss=0.1417:  88%|████████▊ | 70/80 [00:02<00:00, 32.61it/s]

builtin sparse loss=0.1416:  88%|████████▊ | 70/80 [00:02<00:00, 32.61it/s]

builtin sparse loss=0.1414:  88%|████████▊ | 70/80 [00:02<00:00, 32.61it/s]

builtin sparse loss=0.1413:  88%|████████▊ | 70/80 [00:02<00:00, 32.61it/s]

builtin sparse loss=0.1413:  88%|████████▊ | 70/80 [00:02<00:00, 32.61it/s]

builtin sparse loss=0.1413:  92%|█████████▎| 74/80 [00:02<00:00, 32.60it/s]

builtin sparse loss=0.1412:  92%|█████████▎| 74/80 [00:02<00:00, 32.60it/s]

builtin sparse loss=0.1412:  92%|█████████▎| 74/80 [00:02<00:00, 32.60it/s]

builtin sparse loss=0.1411:  92%|█████████▎| 74/80 [00:02<00:00, 32.60it/s]

builtin sparse loss=0.1411:  92%|█████████▎| 74/80 [00:02<00:00, 32.60it/s]

builtin sparse loss=0.1411:  98%|█████████▊| 78/80 [00:02<00:00, 32.99it/s]

builtin sparse loss=0.1411:  98%|█████████▊| 78/80 [00:02<00:00, 32.99it/s]

builtin sparse loss=0.1411:  98%|█████████▊| 78/80 [00:02<00:00, 32.99it/s]

builtin sparse loss=0.1411: 100%|██████████| 80/80 [00:02<00:00, 32.40it/s]

,name,similarity,test_acc,pattern_gini,locality_7x7,class_selectivity,top_sigma_frac
0,provided Sparse r32,0.858908,0.9492,0.440377,0.264228,0.106274,0.295426

,name,similarity,test_acc,pattern_gini,locality_7x7,class_selectivity,top_sigma_frac
0,provided Sparse r32,0.858908,0.9492,0.440377,0.264228,0.106274,0.295426

In [8]:
plus, minus, down, sigma = builtin.decompose()
fig = component_figure(plus.cpu(), minus.cpu(), down.cpu(), sigma.cpu(), k=10, title="Provided Sparse baseline")
save_fig(fig, "components_provided_sparse_baseline")

In [9]:
plot_sigma(sigma.cpu(), "provided Sparse baseline")

## Custom Factorized Models

In [10]:
@dataclass
class RegConfig:
    l1: float = 0.0
    tv: float = 0.0
    d_l1: float = 0.0
    symmetry: float = 0.0
    duplicate: float = 0.0


class BaseFactorModel(nn.Module):
    name = "base"

    def tensor(self):
        raise NotImplementedError

    def component_activations(self, x):
        raise NotImplementedError

    def component_strengths(self):
        raise NotImplementedError

    def decompose(self):
        raise NotImplementedError

    def forward(self, x, mask=None):
        acts = self.component_activations(x)
        if mask is not None:
            acts = acts * mask.to(acts.device)
        return acts @ self.down().T

    def down(self):
        return self.raw_down

    def regularizer(self, cfg: RegConfig):
        plus, minus, down, _ = self.decompose()
        reg = plus.new_tensor(0.0)
        if cfg.l1:
            reg = reg + cfg.l1 * (plus.abs().mean() + minus.abs().mean())
        if cfg.tv:
            reg = reg + cfg.tv * (total_variation(plus) + total_variation(minus))
        if cfg.d_l1:
            reg = reg + cfg.d_l1 * down.abs().mean()
        if cfg.duplicate:
            patterns = normalize_columns(torch.cat([plus, minus], dim=1))
            gram = patterns.T @ patterns
            gram = gram - torch.eye(gram.shape[0], device=gram.device, dtype=gram.dtype)
            reg = reg + cfg.duplicate * gram.square().mean()
        return reg


class CPFactorModel(BaseFactorModel):
    name = "cp"

    def __init__(self, rank=64, scale=0.02):
        super().__init__()
        self.raw_left = nn.Parameter(scale * torch.randn(784, rank))
        self.raw_right = nn.Parameter(scale * torch.randn(784, rank))
        self.raw_down = nn.Parameter(scale * torch.randn(10, rank))

    def left(self):
        return self.raw_left

    def right(self):
        return self.raw_right

    def tensor(self):
        t = einsum(self.down(), self.left(), self.right(), "c r, i r, j r -> c i j")
        return 0.5 * (t + t.mT)

    def component_activations(self, x):
        return (x @ self.left()) * (x @ self.right())

    def component_strengths(self):
        return self.left().norm(dim=0) * self.right().norm(dim=0) * self.down().norm(dim=0)

    def decompose(self):
        l, r, d = self.left(), self.right(), self.down()
        plus = normalize_columns(l + r)
        minus = normalize_columns(l - r)
        sigma = self.component_strengths()
        order = sigma.argsort(descending=True)
        return plus[:, order], minus[:, order], d[:, order], sigma[order]

    def regularizer(self, cfg: RegConfig):
        reg = super().regularizer(cfg)
        if cfg.symmetry:
            reg = reg + cfg.symmetry * (self.left() - self.right()).square().mean()
        return reg


class SymmetricFactorModel(BaseFactorModel):
    name = "symmetric"

    def __init__(self, rank=64, scale=0.02, nonnegative=False):
        super().__init__()
        init = scale * torch.randn(784, rank)
        if nonnegative:
            init = init - 4.0
        self.raw_v = nn.Parameter(init)
        self.raw_down = nn.Parameter(scale * torch.randn(10, rank))
        self.nonnegative = nonnegative

    def v(self):
        return F.softplus(self.raw_v) if self.nonnegative else self.raw_v

    def tensor(self):
        return einsum(self.down(), self.v(), self.v(), "c r, i r, j r -> c i j")

    def component_activations(self, x):
        return (x @ self.v()).square()

    def component_strengths(self):
        return self.v().norm(dim=0).square() * self.down().norm(dim=0)

    def decompose(self):
        v, d = self.v(), self.down()
        plus = normalize_columns(v)
        minus = torch.zeros_like(plus)
        sigma = self.component_strengths()
        order = sigma.argsort(descending=True)
        return plus[:, order], minus[:, order], d[:, order], sigma[order]


class EvidenceSplitModel(BaseFactorModel):
    name = "evidence_split"

    def __init__(self, rank=64, scale=0.02, nonnegative=False):
        super().__init__()
        init_pos = scale * torch.randn(784, rank)
        init_neg = scale * torch.randn(784, rank)
        if nonnegative:
            init_pos = init_pos - 4.0
            init_neg = init_neg - 4.0
        self.raw_pos = nn.Parameter(init_pos)
        self.raw_neg = nn.Parameter(init_neg)
        self.raw_down = nn.Parameter(scale * torch.randn(10, rank))
        self.nonnegative = nonnegative

    def pos(self):
        return F.softplus(self.raw_pos) if self.nonnegative else self.raw_pos

    def neg(self):
        return F.softplus(self.raw_neg) if self.nonnegative else self.raw_neg

    def tensor(self):
        d = self.down()
        return einsum(d, self.pos(), self.pos(), "c r, i r, j r -> c i j") - einsum(
            d, self.neg(), self.neg(), "c r, i r, j r -> c i j"
        )

    def component_activations(self, x):
        return (x @ self.pos()).square() - (x @ self.neg()).square()

    def decompose(self):
        p, n, d = self.pos(), self.neg(), self.down()
        plus = normalize_columns(p)
        minus = normalize_columns(n)
        sigma = (p.norm(dim=0).square() + n.norm(dim=0).square()) * d.norm(dim=0)
        order = sigma.argsort(descending=True)
        return plus[:, order], minus[:, order], d[:, order], sigma[order]

In [11]:
def fit_factor_model(
    factor_model,
    name,
    target=B,
    steps=500,
    lr=0.03,
    reg=RegConfig(),
    seed=0,
    progress=True,
):
    if seed is not None:
        set_seed(seed)
    factor_model = factor_model.to(device)
    optimizer = torch.optim.AdamW(factor_model.parameters(), lr=lr)
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=steps)
    history = []

    iterator = range(steps)
    if progress:
        iterator = tqdm(iterator, desc=name)

    torch.set_grad_enabled(True)
    for step in iterator:
        approx = factor_model.tensor()
        recon = 1 - cosine_to_target(approx, target)
        penalty = factor_model.regularizer(reg)
        loss = recon + penalty

        optimizer.zero_grad(set_to_none=True)
        loss.backward()
        optimizer.step()
        scheduler.step()

        if step % max(1, steps // 50) == 0 or step == steps - 1:
            row = {
                "step": step,
                "loss": loss.item(),
                "recon_loss": recon.item(),
                "penalty": penalty.item(),
                "similarity": (1 - recon).item(),
            }
            history.append(row)
            if progress:
                iterator.set_description(f"{name} sim={row['similarity']:.4f}")
    torch.set_grad_enabled(False)
    return factor_model, history


def plot_history(history, name):
    if pd is not None:
        df = pd.DataFrame(history)
        fig = px.line(df, x="step", y=["recon_loss", "penalty"], title=f"Training losses: {name}", template="plotly_white")
    else:
        fig = px.line(history, x="step", y="recon_loss", title=f"Training loss: {name}", template="plotly_white")
    return save_fig(fig, f"history_{name.replace(' ', '_').lower()}")

## Variant Grid

In [12]:
variant_specs = [
    dict(
        name=f"cp r{BASE_RANK} symmetry-soft",
        factory=lambda: CPFactorModel(rank=BASE_RANK),
        steps=int(350 * VARIANT_STEP_SCALE),
        lr=0.03,
        reg=RegConfig(symmetry=0.05),
        seed=1,
    ),
    dict(
        name=f"symmetric r{BASE_RANK}",
        factory=lambda: SymmetricFactorModel(rank=BASE_RANK),
        steps=int(450 * VARIANT_STEP_SCALE),
        lr=0.04,
        reg=RegConfig(),
        seed=2,
    ),
    dict(
        name=f"symmetric sparse smooth r{BASE_RANK}",
        factory=lambda: SymmetricFactorModel(rank=BASE_RANK),
        steps=int(550 * VARIANT_STEP_SCALE),
        lr=0.04,
        reg=RegConfig(l1=2e-4, tv=2e-3, d_l1=2e-4, duplicate=2e-3),
        seed=3,
    ),
    dict(
        name=f"evidence split r{BASE_RANK}",
        factory=lambda: EvidenceSplitModel(rank=BASE_RANK),
        steps=int(550 * VARIANT_STEP_SCALE),
        lr=0.035,
        reg=RegConfig(),
        seed=4,
    ),
    dict(
        name=f"evidence split sparse smooth r{BASE_RANK}",
        factory=lambda: EvidenceSplitModel(rank=BASE_RANK),
        steps=int(650 * VARIANT_STEP_SCALE),
        lr=0.035,
        reg=RegConfig(l1=2e-4, tv=2e-3, d_l1=2e-4, duplicate=1e-3),
        seed=5,
    ),
    dict(
        name=f"nonnegative strokes r{LARGE_RANK}",
        factory=lambda: EvidenceSplitModel(rank=LARGE_RANK, nonnegative=True),
        steps=int(650 * VARIANT_STEP_SCALE),
        lr=0.03,
        reg=RegConfig(l1=3e-4, tv=2e-3, d_l1=2e-4, duplicate=1e-3),
        seed=6,
    ),
]

trained = {f"provided Sparse r{BASE_RANK}": builtin}
histories = {}
rows = [builtin_row]

for spec in variant_specs:
    set_seed(spec["seed"])
    factor, history = fit_factor_model(
        spec["factory"](),
        spec["name"],
        steps=spec["steps"],
        lr=spec["lr"],
        reg=spec["reg"],
        seed=None,
    )
    trained[spec["name"]] = factor
    histories[spec["name"]] = history
    rows.append(metric_dict(spec["name"], factor))

results = show_table(rows, sort_by="similarity")

cp r32 symmetry-soft:   0%|          | 0/77 [00:00<?, ?it/s]

cp r32 symmetry-soft sim=0.0008:   0%|          | 0/77 [00:00<?, ?it/s]

cp r32 symmetry-soft sim=0.0687:   0%|          | 0/77 [00:00<?, ?it/s]

cp r32 symmetry-soft sim=0.3353:   0%|          | 0/77 [00:00<?, ?it/s]

cp r32 symmetry-soft sim=0.3353:   4%|▍         | 3/77 [00:00<00:02, 28.60it/s]

cp r32 symmetry-soft sim=0.4919:   4%|▍         | 3/77 [00:00<00:02, 28.60it/s]

cp r32 symmetry-soft sim=0.5801:   4%|▍         | 3/77 [00:00<00:02, 28.60it/s]

cp r32 symmetry-soft sim=0.6332:   4%|▍         | 3/77 [00:00<00:02, 28.60it/s]

cp r32 symmetry-soft sim=0.6687:   4%|▍         | 3/77 [00:00<00:02, 28.60it/s]

cp r32 symmetry-soft sim=0.6943:   4%|▍         | 3/77 [00:00<00:02, 28.60it/s]

cp r32 symmetry-soft sim=0.7140:   4%|▍         | 3/77 [00:00<00:02, 28.60it/s]

cp r32 symmetry-soft sim=0.7140:  12%|█▏        | 9/77 [00:00<00:01, 45.56it/s]

cp r32 symmetry-soft sim=0.7300:  12%|█▏        | 9/77 [00:00<00:01, 45.56it/s]

cp r32 symmetry-soft sim=0.7434:  12%|█▏        | 9/77 [00:00<00:01, 45.56it/s]

cp r32 symmetry-soft sim=0.7549:  12%|█▏        | 9/77 [00:00<00:01, 45.56it/s]

cp r32 symmetry-soft sim=0.7649:  12%|█▏        | 9/77 [00:00<00:01, 45.56it/s]

cp r32 symmetry-soft sim=0.7737:  12%|█▏        | 9/77 [00:00<00:01, 45.56it/s]

cp r32 symmetry-soft sim=0.7737:  18%|█▊        | 14/77 [00:00<00:01, 45.52it/s]

cp r32 symmetry-soft sim=0.7815:  18%|█▊        | 14/77 [00:00<00:01, 45.52it/s]

cp r32 symmetry-soft sim=0.7883:  18%|█▊        | 14/77 [00:00<00:01, 45.52it/s]

cp r32 symmetry-soft sim=0.7943:  18%|█▊        | 14/77 [00:00<00:01, 45.52it/s]

cp r32 symmetry-soft sim=0.7996:  18%|█▊        | 14/77 [00:00<00:01, 45.52it/s]

cp r32 symmetry-soft sim=0.8044:  18%|█▊        | 14/77 [00:00<00:01, 45.52it/s]

cp r32 symmetry-soft sim=0.8087:  18%|█▊        | 14/77 [00:00<00:01, 45.52it/s]

cp r32 symmetry-soft sim=0.8087:  26%|██▌       | 20/77 [00:00<00:01, 48.73it/s]

cp r32 symmetry-soft sim=0.8126:  26%|██▌       | 20/77 [00:00<00:01, 48.73it/s]

cp r32 symmetry-soft sim=0.8162:  26%|██▌       | 20/77 [00:00<00:01, 48.73it/s]

cp r32 symmetry-soft sim=0.8195:  26%|██▌       | 20/77 [00:00<00:01, 48.73it/s]

cp r32 symmetry-soft sim=0.8225:  26%|██▌       | 20/77 [00:00<00:01, 48.73it/s]

cp r32 symmetry-soft sim=0.8253:  26%|██▌       | 20/77 [00:00<00:01, 48.73it/s]

cp r32 symmetry-soft sim=0.8278:  26%|██▌       | 20/77 [00:00<00:01, 48.73it/s]

cp r32 symmetry-soft sim=0.8278:  34%|███▍      | 26/77 [00:00<00:01, 50.09it/s]

cp r32 symmetry-soft sim=0.8302:  34%|███▍      | 26/77 [00:00<00:01, 50.09it/s]

cp r32 symmetry-soft sim=0.8324:  34%|███▍      | 26/77 [00:00<00:01, 50.09it/s]

cp r32 symmetry-soft sim=0.8344:  34%|███▍      | 26/77 [00:00<00:01, 50.09it/s]

cp r32 symmetry-soft sim=0.8363:  34%|███▍      | 26/77 [00:00<00:01, 50.09it/s]

cp r32 symmetry-soft sim=0.8381:  34%|███▍      | 26/77 [00:00<00:01, 50.09it/s]

cp r32 symmetry-soft sim=0.8381:  40%|████      | 31/77 [00:00<00:00, 48.64it/s]

cp r32 symmetry-soft sim=0.8397:  40%|████      | 31/77 [00:00<00:00, 48.64it/s]

cp r32 symmetry-soft sim=0.8413:  40%|████      | 31/77 [00:00<00:00, 48.64it/s]

cp r32 symmetry-soft sim=0.8427:  40%|████      | 31/77 [00:00<00:00, 48.64it/s]

cp r32 symmetry-soft sim=0.8441:  40%|████      | 31/77 [00:00<00:00, 48.64it/s]

cp r32 symmetry-soft sim=0.8453:  40%|████      | 31/77 [00:00<00:00, 48.64it/s]

cp r32 symmetry-soft sim=0.8465:  40%|████      | 31/77 [00:00<00:00, 48.64it/s]

cp r32 symmetry-soft sim=0.8465:  48%|████▊     | 37/77 [00:00<00:00, 48.84it/s]

cp r32 symmetry-soft sim=0.8476:  48%|████▊     | 37/77 [00:00<00:00, 48.84it/s]

cp r32 symmetry-soft sim=0.8486:  48%|████▊     | 37/77 [00:00<00:00, 48.84it/s]

cp r32 symmetry-soft sim=0.8496:  48%|████▊     | 37/77 [00:00<00:00, 48.84it/s]

cp r32 symmetry-soft sim=0.8505:  48%|████▊     | 37/77 [00:00<00:00, 48.84it/s]

cp r32 symmetry-soft sim=0.8514:  48%|████▊     | 37/77 [00:00<00:00, 48.84it/s]

cp r32 symmetry-soft sim=0.8514:  55%|█████▍    | 42/77 [00:00<00:00, 47.87it/s]

cp r32 symmetry-soft sim=0.8522:  55%|█████▍    | 42/77 [00:00<00:00, 47.87it/s]

cp r32 symmetry-soft sim=0.8529:  55%|█████▍    | 42/77 [00:00<00:00, 47.87it/s]

cp r32 symmetry-soft sim=0.8536:  55%|█████▍    | 42/77 [00:00<00:00, 47.87it/s]

cp r32 symmetry-soft sim=0.8543:  55%|█████▍    | 42/77 [00:00<00:00, 47.87it/s]

cp r32 symmetry-soft sim=0.8549:  55%|█████▍    | 42/77 [00:01<00:00, 47.87it/s]

cp r32 symmetry-soft sim=0.8549:  61%|██████    | 47/77 [00:01<00:00, 46.25it/s]

cp r32 symmetry-soft sim=0.8554:  61%|██████    | 47/77 [00:01<00:00, 46.25it/s]

cp r32 symmetry-soft sim=0.8560:  61%|██████    | 47/77 [00:01<00:00, 46.25it/s]

cp r32 symmetry-soft sim=0.8565:  61%|██████    | 47/77 [00:01<00:00, 46.25it/s]

cp r32 symmetry-soft sim=0.8569:  61%|██████    | 47/77 [00:01<00:00, 46.25it/s]

cp r32 symmetry-soft sim=0.8574:  61%|██████    | 47/77 [00:01<00:00, 46.25it/s]

cp r32 symmetry-soft sim=0.8574:  68%|██████▊   | 52/77 [00:01<00:00, 45.38it/s]

cp r32 symmetry-soft sim=0.8577:  68%|██████▊   | 52/77 [00:01<00:00, 45.38it/s]

cp r32 symmetry-soft sim=0.8581:  68%|██████▊   | 52/77 [00:01<00:00, 45.38it/s]

cp r32 symmetry-soft sim=0.8584:  68%|██████▊   | 52/77 [00:01<00:00, 45.38it/s]

cp r32 symmetry-soft sim=0.8588:  68%|██████▊   | 52/77 [00:01<00:00, 45.38it/s]

cp r32 symmetry-soft sim=0.8590:  68%|██████▊   | 52/77 [00:01<00:00, 45.38it/s]

cp r32 symmetry-soft sim=0.8590:  74%|███████▍  | 57/77 [00:01<00:00, 42.98it/s]

cp r32 symmetry-soft sim=0.8593:  74%|███████▍  | 57/77 [00:01<00:00, 42.98it/s]

cp r32 symmetry-soft sim=0.8595:  74%|███████▍  | 57/77 [00:01<00:00, 42.98it/s]

cp r32 symmetry-soft sim=0.8597:  74%|███████▍  | 57/77 [00:01<00:00, 42.98it/s]

cp r32 symmetry-soft sim=0.8599:  74%|███████▍  | 57/77 [00:01<00:00, 42.98it/s]

cp r32 symmetry-soft sim=0.8601:  74%|███████▍  | 57/77 [00:01<00:00, 42.98it/s]

cp r32 symmetry-soft sim=0.8601:  81%|████████  | 62/77 [00:01<00:00, 39.46it/s]

cp r32 symmetry-soft sim=0.8602:  81%|████████  | 62/77 [00:01<00:00, 39.46it/s]

cp r32 symmetry-soft sim=0.8604:  81%|████████  | 62/77 [00:01<00:00, 39.46it/s]

cp r32 symmetry-soft sim=0.8605:  81%|████████  | 62/77 [00:01<00:00, 39.46it/s]

cp r32 symmetry-soft sim=0.8606:  81%|████████  | 62/77 [00:01<00:00, 39.46it/s]

cp r32 symmetry-soft sim=0.8607:  81%|████████  | 62/77 [00:01<00:00, 39.46it/s]

cp r32 symmetry-soft sim=0.8607:  87%|████████▋ | 67/77 [00:01<00:00, 35.33it/s]

cp r32 symmetry-soft sim=0.8607:  87%|████████▋ | 67/77 [00:01<00:00, 35.33it/s]

cp r32 symmetry-soft sim=0.8608:  87%|████████▋ | 67/77 [00:01<00:00, 35.33it/s]

cp r32 symmetry-soft sim=0.8609:  87%|████████▋ | 67/77 [00:01<00:00, 35.33it/s]

cp r32 symmetry-soft sim=0.8609:  87%|████████▋ | 67/77 [00:01<00:00, 35.33it/s]

cp r32 symmetry-soft sim=0.8609:  92%|█████████▏| 71/77 [00:01<00:00, 33.33it/s]

cp r32 symmetry-soft sim=0.8609:  92%|█████████▏| 71/77 [00:01<00:00, 33.33it/s]

cp r32 symmetry-soft sim=0.8609:  92%|█████████▏| 71/77 [00:01<00:00, 33.33it/s]

cp r32 symmetry-soft sim=0.8610:  92%|█████████▏| 71/77 [00:01<00:00, 33.33it/s]

cp r32 symmetry-soft sim=0.8610:  92%|█████████▏| 71/77 [00:01<00:00, 33.33it/s]

cp r32 symmetry-soft sim=0.8610:  92%|█████████▏| 71/77 [00:01<00:00, 33.33it/s]

cp r32 symmetry-soft sim=0.8610:  99%|█████████▊| 76/77 [00:01<00:00, 35.28it/s]

cp r32 symmetry-soft sim=0.8610:  99%|█████████▊| 76/77 [00:01<00:00, 35.28it/s]

cp r32 symmetry-soft sim=0.8610: 100%|██████████| 77/77 [00:01<00:00, 41.29it/s]

symmetric r32:   0%|          | 0/99 [00:00<?, ?it/s]

symmetric r32 sim=-0.0002:   0%|          | 0/99 [00:00<?, ?it/s]

symmetric r32 sim=0.0717:   0%|          | 0/99 [00:00<?, ?it/s]

symmetric r32 sim=0.2917:   0%|          | 0/99 [00:00<?, ?it/s]

symmetric r32 sim=0.4299:   0%|          | 0/99 [00:00<?, ?it/s]

symmetric r32 sim=0.5109:   0%|          | 0/99 [00:00<?, ?it/s]

symmetric r32 sim=0.5109:   5%|▌         | 5/99 [00:00<00:01, 49.64it/s]

symmetric r32 sim=0.5610:   5%|▌         | 5/99 [00:00<00:01, 49.64it/s]

symmetric r32 sim=0.5947:   5%|▌         | 5/99 [00:00<00:01, 49.64it/s]

symmetric r32 sim=0.6187:   5%|▌         | 5/99 [00:00<00:01, 49.64it/s]

symmetric r32 sim=0.6367:   5%|▌         | 5/99 [00:00<00:01, 49.64it/s]

symmetric r32 sim=0.6512:   5%|▌         | 5/99 [00:00<00:01, 49.64it/s]

symmetric r32 sim=0.6512:  10%|█         | 10/99 [00:00<00:01, 45.54it/s]

symmetric r32 sim=0.6635:  10%|█         | 10/99 [00:00<00:01, 45.54it/s]

symmetric r32 sim=0.6742:  10%|█         | 10/99 [00:00<00:01, 45.54it/s]

symmetric r32 sim=0.6837:  10%|█         | 10/99 [00:00<00:01, 45.54it/s]

symmetric r32 sim=0.6920:  10%|█         | 10/99 [00:00<00:01, 45.54it/s]

symmetric r32 sim=0.6993:  10%|█         | 10/99 [00:00<00:01, 45.54it/s]

symmetric r32 sim=0.7057:  10%|█         | 10/99 [00:00<00:01, 45.54it/s]

symmetric r32 sim=0.7057:  16%|█▌        | 16/99 [00:00<00:01, 48.88it/s]

symmetric r32 sim=0.7112:  16%|█▌        | 16/99 [00:00<00:01, 48.88it/s]

symmetric r32 sim=0.7161:  16%|█▌        | 16/99 [00:00<00:01, 48.88it/s]

symmetric r32 sim=0.7205:  16%|█▌        | 16/99 [00:00<00:01, 48.88it/s]

symmetric r32 sim=0.7246:  16%|█▌        | 16/99 [00:00<00:01, 48.88it/s]

symmetric r32 sim=0.7282:  16%|█▌        | 16/99 [00:00<00:01, 48.88it/s]

symmetric r32 sim=0.7316:  16%|█▌        | 16/99 [00:00<00:01, 48.88it/s]

symmetric r32 sim=0.7316:  22%|██▏       | 22/99 [00:00<00:01, 51.17it/s]

symmetric r32 sim=0.7346:  22%|██▏       | 22/99 [00:00<00:01, 51.17it/s]

symmetric r32 sim=0.7374:  22%|██▏       | 22/99 [00:00<00:01, 51.17it/s]

symmetric r32 sim=0.7399:  22%|██▏       | 22/99 [00:00<00:01, 51.17it/s]

symmetric r32 sim=0.7423:  22%|██▏       | 22/99 [00:00<00:01, 51.17it/s]

symmetric r32 sim=0.7444:  22%|██▏       | 22/99 [00:00<00:01, 51.17it/s]

symmetric r32 sim=0.7464:  22%|██▏       | 22/99 [00:00<00:01, 51.17it/s]

symmetric r32 sim=0.7464:  28%|██▊       | 28/99 [00:00<00:01, 52.12it/s]

symmetric r32 sim=0.7482:  28%|██▊       | 28/99 [00:00<00:01, 52.12it/s]

symmetric r32 sim=0.7499:  28%|██▊       | 28/99 [00:00<00:01, 52.12it/s]

symmetric r32 sim=0.7515:  28%|██▊       | 28/99 [00:00<00:01, 52.12it/s]

symmetric r32 sim=0.7530:  28%|██▊       | 28/99 [00:00<00:01, 52.12it/s]

symmetric r32 sim=0.7543:  28%|██▊       | 28/99 [00:00<00:01, 52.12it/s]

symmetric r32 sim=0.7557:  28%|██▊       | 28/99 [00:00<00:01, 52.12it/s]

symmetric r32 sim=0.7557:  34%|███▍      | 34/99 [00:00<00:01, 51.04it/s]

symmetric r32 sim=0.7569:  34%|███▍      | 34/99 [00:00<00:01, 51.04it/s]

symmetric r32 sim=0.7580:  34%|███▍      | 34/99 [00:00<00:01, 51.04it/s]

symmetric r32 sim=0.7591:  34%|███▍      | 34/99 [00:00<00:01, 51.04it/s]

symmetric r32 sim=0.7602:  34%|███▍      | 34/99 [00:00<00:01, 51.04it/s]

symmetric r32 sim=0.7611:  34%|███▍      | 34/99 [00:00<00:01, 51.04it/s]

symmetric r32 sim=0.7620:  34%|███▍      | 34/99 [00:00<00:01, 51.04it/s]

symmetric r32 sim=0.7620:  40%|████      | 40/99 [00:00<00:01, 49.03it/s]

symmetric r32 sim=0.7629:  40%|████      | 40/99 [00:00<00:01, 49.03it/s]

symmetric r32 sim=0.7637:  40%|████      | 40/99 [00:00<00:01, 49.03it/s]

symmetric r32 sim=0.7645:  40%|████      | 40/99 [00:00<00:01, 49.03it/s]

symmetric r32 sim=0.7653:  40%|████      | 40/99 [00:00<00:01, 49.03it/s]

symmetric r32 sim=0.7660:  40%|████      | 40/99 [00:00<00:01, 49.03it/s]

symmetric r32 sim=0.7667:  40%|████      | 40/99 [00:00<00:01, 49.03it/s]

symmetric r32 sim=0.7667:  46%|████▋     | 46/99 [00:00<00:01, 50.76it/s]

symmetric r32 sim=0.7673:  46%|████▋     | 46/99 [00:00<00:01, 50.76it/s]

symmetric r32 sim=0.7680:  46%|████▋     | 46/99 [00:00<00:01, 50.76it/s]

symmetric r32 sim=0.7686:  46%|████▋     | 46/99 [00:00<00:01, 50.76it/s]

symmetric r32 sim=0.7692:  46%|████▋     | 46/99 [00:00<00:01, 50.76it/s]

symmetric r32 sim=0.7697:  46%|████▋     | 46/99 [00:00<00:01, 50.76it/s]

symmetric r32 sim=0.7703:  46%|████▋     | 46/99 [00:01<00:01, 50.76it/s]

symmetric r32 sim=0.7708:  46%|████▋     | 46/99 [00:01<00:01, 50.76it/s]

symmetric r32 sim=0.7708:  54%|█████▎    | 53/99 [00:01<00:00, 54.36it/s]

symmetric r32 sim=0.7713:  54%|█████▎    | 53/99 [00:01<00:00, 54.36it/s]

symmetric r32 sim=0.7717:  54%|█████▎    | 53/99 [00:01<00:00, 54.36it/s]

symmetric r32 sim=0.7722:  54%|█████▎    | 53/99 [00:01<00:00, 54.36it/s]

symmetric r32 sim=0.7726:  54%|█████▎    | 53/99 [00:01<00:00, 54.36it/s]

symmetric r32 sim=0.7730:  54%|█████▎    | 53/99 [00:01<00:00, 54.36it/s]

symmetric r32 sim=0.7734:  54%|█████▎    | 53/99 [00:01<00:00, 54.36it/s]

symmetric r32 sim=0.7734:  60%|█████▉    | 59/99 [00:01<00:00, 55.33it/s]

symmetric r32 sim=0.7738:  60%|█████▉    | 59/99 [00:01<00:00, 55.33it/s]

symmetric r32 sim=0.7741:  60%|█████▉    | 59/99 [00:01<00:00, 55.33it/s]

symmetric r32 sim=0.7745:  60%|█████▉    | 59/99 [00:01<00:00, 55.33it/s]

symmetric r32 sim=0.7748:  60%|█████▉    | 59/99 [00:01<00:00, 55.33it/s]

symmetric r32 sim=0.7751:  60%|█████▉    | 59/99 [00:01<00:00, 55.33it/s]

symmetric r32 sim=0.7754:  60%|█████▉    | 59/99 [00:01<00:00, 55.33it/s]

symmetric r32 sim=0.7754:  66%|██████▌   | 65/99 [00:01<00:00, 55.76it/s]

symmetric r32 sim=0.7757:  66%|██████▌   | 65/99 [00:01<00:00, 55.76it/s]

symmetric r32 sim=0.7759:  66%|██████▌   | 65/99 [00:01<00:00, 55.76it/s]

symmetric r32 sim=0.7762:  66%|██████▌   | 65/99 [00:01<00:00, 55.76it/s]

symmetric r32 sim=0.7764:  66%|██████▌   | 65/99 [00:01<00:00, 55.76it/s]

symmetric r32 sim=0.7766:  66%|██████▌   | 65/99 [00:01<00:00, 55.76it/s]

symmetric r32 sim=0.7768:  66%|██████▌   | 65/99 [00:01<00:00, 55.76it/s]

symmetric r32 sim=0.7768:  72%|███████▏  | 71/99 [00:01<00:00, 53.99it/s]

symmetric r32 sim=0.7770:  72%|███████▏  | 71/99 [00:01<00:00, 53.99it/s]

symmetric r32 sim=0.7772:  72%|███████▏  | 71/99 [00:01<00:00, 53.99it/s]

symmetric r32 sim=0.7773:  72%|███████▏  | 71/99 [00:01<00:00, 53.99it/s]

symmetric r32 sim=0.7775:  72%|███████▏  | 71/99 [00:01<00:00, 53.99it/s]

symmetric r32 sim=0.7776:  72%|███████▏  | 71/99 [00:01<00:00, 53.99it/s]

symmetric r32 sim=0.7778:  72%|███████▏  | 71/99 [00:01<00:00, 53.99it/s]

symmetric r32 sim=0.7778:  78%|███████▊  | 77/99 [00:01<00:00, 53.32it/s]

symmetric r32 sim=0.7779:  78%|███████▊  | 77/99 [00:01<00:00, 53.32it/s]

symmetric r32 sim=0.7780:  78%|███████▊  | 77/99 [00:01<00:00, 53.32it/s]

symmetric r32 sim=0.7781:  78%|███████▊  | 77/99 [00:01<00:00, 53.32it/s]

symmetric r32 sim=0.7782:  78%|███████▊  | 77/99 [00:01<00:00, 53.32it/s]

symmetric r32 sim=0.7783:  78%|███████▊  | 77/99 [00:01<00:00, 53.32it/s]

symmetric r32 sim=0.7784:  78%|███████▊  | 77/99 [00:01<00:00, 53.32it/s]

symmetric r32 sim=0.7784:  84%|████████▍ | 83/99 [00:01<00:00, 53.26it/s]

symmetric r32 sim=0.7784:  84%|████████▍ | 83/99 [00:01<00:00, 53.26it/s]

symmetric r32 sim=0.7785:  84%|████████▍ | 83/99 [00:01<00:00, 53.26it/s]

symmetric r32 sim=0.7785:  84%|████████▍ | 83/99 [00:01<00:00, 53.26it/s]

symmetric r32 sim=0.7786:  84%|████████▍ | 83/99 [00:01<00:00, 53.26it/s]

symmetric r32 sim=0.7786:  84%|████████▍ | 83/99 [00:01<00:00, 53.26it/s]

symmetric r32 sim=0.7787:  84%|████████▍ | 83/99 [00:01<00:00, 53.26it/s]

symmetric r32 sim=0.7787:  90%|████████▉ | 89/99 [00:01<00:00, 54.97it/s]

symmetric r32 sim=0.7787:  90%|████████▉ | 89/99 [00:01<00:00, 54.97it/s]

symmetric r32 sim=0.7787:  90%|████████▉ | 89/99 [00:01<00:00, 54.97it/s]

symmetric r32 sim=0.7787:  90%|████████▉ | 89/99 [00:01<00:00, 54.97it/s]

symmetric r32 sim=0.7788:  90%|████████▉ | 89/99 [00:01<00:00, 54.97it/s]

symmetric r32 sim=0.7788:  90%|████████▉ | 89/99 [00:01<00:00, 54.97it/s]

symmetric r32 sim=0.7788:  90%|████████▉ | 89/99 [00:01<00:00, 54.97it/s]

symmetric r32 sim=0.7788:  96%|█████████▌| 95/99 [00:01<00:00, 54.59it/s]

symmetric r32 sim=0.7788:  96%|█████████▌| 95/99 [00:01<00:00, 54.59it/s]

symmetric r32 sim=0.7788:  96%|█████████▌| 95/99 [00:01<00:00, 54.59it/s]

symmetric r32 sim=0.7788:  96%|█████████▌| 95/99 [00:01<00:00, 54.59it/s]

symmetric r32 sim=0.7788:  96%|█████████▌| 95/99 [00:01<00:00, 54.59it/s]

symmetric r32 sim=0.7788: 100%|██████████| 99/99 [00:01<00:00, 52.90it/s]

symmetric sparse smooth r32:   0%|          | 0/121 [00:00<?, ?it/s]

symmetric sparse smooth r32 sim=0.0004:   0%|          | 0/121 [00:00<?, ?it/s]

symmetric sparse smooth r32 sim=0.0004:   1%|          | 1/121 [00:00<00:12,  9.95it/s]

symmetric sparse smooth r32 sim=0.2801:   1%|          | 1/121 [00:00<00:12,  9.95it/s]

symmetric sparse smooth r32 sim=0.2801:   3%|▎         | 4/121 [00:00<00:05, 21.46it/s]

symmetric sparse smooth r32 sim=0.4731:   3%|▎         | 4/121 [00:00<00:05, 21.46it/s]

symmetric sparse smooth r32 sim=0.5597:   3%|▎         | 4/121 [00:00<00:05, 21.46it/s]

symmetric sparse smooth r32 sim=0.6089:   3%|▎         | 4/121 [00:00<00:05, 21.46it/s]

symmetric sparse smooth r32 sim=0.6089:   8%|▊         | 10/121 [00:00<00:02, 38.85it/s]

symmetric sparse smooth r32 sim=0.6418:   8%|▊         | 10/121 [00:00<00:02, 38.85it/s]

symmetric sparse smooth r32 sim=0.6661:   8%|▊         | 10/121 [00:00<00:02, 38.85it/s]

symmetric sparse smooth r32 sim=0.6839:   8%|▊         | 10/121 [00:00<00:02, 38.85it/s]

symmetric sparse smooth r32 sim=0.6972:   8%|▊         | 10/121 [00:00<00:02, 38.85it/s]

symmetric sparse smooth r32 sim=0.6972:  14%|█▍        | 17/121 [00:00<00:02, 48.67it/s]

symmetric sparse smooth r32 sim=0.7076:  14%|█▍        | 17/121 [00:00<00:02, 48.67it/s]

symmetric sparse smooth r32 sim=0.7163:  14%|█▍        | 17/121 [00:00<00:02, 48.67it/s]

symmetric sparse smooth r32 sim=0.7235:  14%|█▍        | 17/121 [00:00<00:02, 48.67it/s]

symmetric sparse smooth r32 sim=0.7235:  20%|█▉        | 24/121 [00:00<00:01, 55.21it/s]

symmetric sparse smooth r32 sim=0.7296:  20%|█▉        | 24/121 [00:00<00:01, 55.21it/s]

symmetric sparse smooth r32 sim=0.7348:  20%|█▉        | 24/121 [00:00<00:01, 55.21it/s]

symmetric sparse smooth r32 sim=0.7393:  20%|█▉        | 24/121 [00:00<00:01, 55.21it/s]

symmetric sparse smooth r32 sim=0.7393:  25%|██▍       | 30/121 [00:00<00:01, 56.77it/s]

symmetric sparse smooth r32 sim=0.7434:  25%|██▍       | 30/121 [00:00<00:01, 56.77it/s]

symmetric sparse smooth r32 sim=0.7469:  25%|██▍       | 30/121 [00:00<00:01, 56.77it/s]

symmetric sparse smooth r32 sim=0.7502:  25%|██▍       | 30/121 [00:00<00:01, 56.77it/s]

symmetric sparse smooth r32 sim=0.7502:  30%|██▉       | 36/121 [00:00<00:01, 56.72it/s]

symmetric sparse smooth r32 sim=0.7531:  30%|██▉       | 36/121 [00:00<00:01, 56.72it/s]

symmetric sparse smooth r32 sim=0.7559:  30%|██▉       | 36/121 [00:00<00:01, 56.72it/s]

symmetric sparse smooth r32 sim=0.7586:  30%|██▉       | 36/121 [00:00<00:01, 56.72it/s]

symmetric sparse smooth r32 sim=0.7586:  35%|███▍      | 42/121 [00:00<00:01, 56.32it/s]

symmetric sparse smooth r32 sim=0.7610:  35%|███▍      | 42/121 [00:00<00:01, 56.32it/s]

symmetric sparse smooth r32 sim=0.7632:  35%|███▍      | 42/121 [00:00<00:01, 56.32it/s]

symmetric sparse smooth r32 sim=0.7654:  35%|███▍      | 42/121 [00:00<00:01, 56.32it/s]

symmetric sparse smooth r32 sim=0.7654:  40%|███▉      | 48/121 [00:00<00:01, 54.17it/s]

symmetric sparse smooth r32 sim=0.7673:  40%|███▉      | 48/121 [00:00<00:01, 54.17it/s]

symmetric sparse smooth r32 sim=0.7692:  40%|███▉      | 48/121 [00:01<00:01, 54.17it/s]

symmetric sparse smooth r32 sim=0.7708:  40%|███▉      | 48/121 [00:01<00:01, 54.17it/s]

symmetric sparse smooth r32 sim=0.7708:  45%|████▍     | 54/121 [00:01<00:01, 52.75it/s]

symmetric sparse smooth r32 sim=0.7724:  45%|████▍     | 54/121 [00:01<00:01, 52.75it/s]

symmetric sparse smooth r32 sim=0.7739:  45%|████▍     | 54/121 [00:01<00:01, 52.75it/s]

symmetric sparse smooth r32 sim=0.7752:  45%|████▍     | 54/121 [00:01<00:01, 52.75it/s]

symmetric sparse smooth r32 sim=0.7752:  50%|████▉     | 60/121 [00:01<00:01, 50.62it/s]

symmetric sparse smooth r32 sim=0.7764:  50%|████▉     | 60/121 [00:01<00:01, 50.62it/s]

symmetric sparse smooth r32 sim=0.7775:  50%|████▉     | 60/121 [00:01<00:01, 50.62it/s]

symmetric sparse smooth r32 sim=0.7786:  50%|████▉     | 60/121 [00:01<00:01, 50.62it/s]

symmetric sparse smooth r32 sim=0.7786:  55%|█████▍    | 66/121 [00:01<00:01, 49.33it/s]

symmetric sparse smooth r32 sim=0.7795:  55%|█████▍    | 66/121 [00:01<00:01, 49.33it/s]

symmetric sparse smooth r32 sim=0.7804:  55%|█████▍    | 66/121 [00:01<00:01, 49.33it/s]

symmetric sparse smooth r32 sim=0.7812:  55%|█████▍    | 66/121 [00:01<00:01, 49.33it/s]

symmetric sparse smooth r32 sim=0.7812:  59%|█████▊    | 71/121 [00:01<00:01, 46.79it/s]

symmetric sparse smooth r32 sim=0.7820:  59%|█████▊    | 71/121 [00:01<00:01, 46.79it/s]

symmetric sparse smooth r32 sim=0.7827:  59%|█████▊    | 71/121 [00:01<00:01, 46.79it/s]

symmetric sparse smooth r32 sim=0.7833:  59%|█████▊    | 71/121 [00:01<00:01, 46.79it/s]

symmetric sparse smooth r32 sim=0.7833:  64%|██████▎   | 77/121 [00:01<00:00, 46.34it/s]

symmetric sparse smooth r32 sim=0.7839:  64%|██████▎   | 77/121 [00:01<00:00, 46.34it/s]

symmetric sparse smooth r32 sim=0.7844:  64%|██████▎   | 77/121 [00:01<00:00, 46.34it/s]

symmetric sparse smooth r32 sim=0.7844:  68%|██████▊   | 82/121 [00:01<00:00, 47.23it/s]

symmetric sparse smooth r32 sim=0.7848:  68%|██████▊   | 82/121 [00:01<00:00, 47.23it/s]

symmetric sparse smooth r32 sim=0.7853:  68%|██████▊   | 82/121 [00:01<00:00, 47.23it/s]

symmetric sparse smooth r32 sim=0.7856:  68%|██████▊   | 82/121 [00:01<00:00, 47.23it/s]

symmetric sparse smooth r32 sim=0.7856:  72%|███████▏  | 87/121 [00:01<00:00, 45.16it/s]

symmetric sparse smooth r32 sim=0.7860:  72%|███████▏  | 87/121 [00:01<00:00, 45.16it/s]

symmetric sparse smooth r32 sim=0.7863:  72%|███████▏  | 87/121 [00:01<00:00, 45.16it/s]

symmetric sparse smooth r32 sim=0.7863:  76%|███████▌  | 92/121 [00:01<00:00, 45.42it/s]

symmetric sparse smooth r32 sim=0.7865:  76%|███████▌  | 92/121 [00:01<00:00, 45.42it/s]

symmetric sparse smooth r32 sim=0.7868:  76%|███████▌  | 92/121 [00:01<00:00, 45.42it/s]

symmetric sparse smooth r32 sim=0.7870:  76%|███████▌  | 92/121 [00:02<00:00, 45.42it/s]

symmetric sparse smooth r32 sim=0.7870:  80%|████████  | 97/121 [00:02<00:00, 45.41it/s]

symmetric sparse smooth r32 sim=0.7871:  80%|████████  | 97/121 [00:02<00:00, 45.41it/s]

symmetric sparse smooth r32 sim=0.7873:  80%|████████  | 97/121 [00:02<00:00, 45.41it/s]

symmetric sparse smooth r32 sim=0.7874:  80%|████████  | 97/121 [00:02<00:00, 45.41it/s]

symmetric sparse smooth r32 sim=0.7874:  85%|████████▌ | 103/121 [00:02<00:00, 49.13it/s]

symmetric sparse smooth r32 sim=0.7875:  85%|████████▌ | 103/121 [00:02<00:00, 49.13it/s]

symmetric sparse smooth r32 sim=0.7876:  85%|████████▌ | 103/121 [00:02<00:00, 49.13it/s]

symmetric sparse smooth r32 sim=0.7876:  85%|████████▌ | 103/121 [00:02<00:00, 49.13it/s]

symmetric sparse smooth r32 sim=0.7876:  90%|█████████ | 109/121 [00:02<00:00, 51.72it/s]

symmetric sparse smooth r32 sim=0.7877:  90%|█████████ | 109/121 [00:02<00:00, 51.72it/s]

symmetric sparse smooth r32 sim=0.7877:  90%|█████████ | 109/121 [00:02<00:00, 51.72it/s]

symmetric sparse smooth r32 sim=0.7877:  90%|█████████ | 109/121 [00:02<00:00, 51.72it/s]

symmetric sparse smooth r32 sim=0.7877:  95%|█████████▌| 115/121 [00:02<00:00, 53.44it/s]

symmetric sparse smooth r32 sim=0.7877:  95%|█████████▌| 115/121 [00:02<00:00, 53.44it/s]

symmetric sparse smooth r32 sim=0.7877:  95%|█████████▌| 115/121 [00:02<00:00, 53.44it/s]

symmetric sparse smooth r32 sim=0.7878:  95%|█████████▌| 115/121 [00:02<00:00, 53.44it/s]

symmetric sparse smooth r32 sim=0.7878: 100%|██████████| 121/121 [00:02<00:00, 52.72it/s]

symmetric sparse smooth r32 sim=0.7878: 100%|██████████| 121/121 [00:02<00:00, 49.26it/s]

evidence split r32:   0%|          | 0/121 [00:00<?, ?it/s]

evidence split r32 sim=0.0007:   0%|          | 0/121 [00:00<?, ?it/s]

evidence split r32 sim=0.3386:   0%|          | 0/121 [00:00<?, ?it/s]

evidence split r32 sim=0.5783:   0%|          | 0/121 [00:00<?, ?it/s]

evidence split r32 sim=0.5783:   4%|▍         | 5/121 [00:00<00:02, 48.53it/s]

evidence split r32 sim=0.6657:   4%|▍         | 5/121 [00:00<00:02, 48.53it/s]

evidence split r32 sim=0.7096:   4%|▍         | 5/121 [00:00<00:02, 48.53it/s]

evidence split r32 sim=0.7380:   4%|▍         | 5/121 [00:00<00:02, 48.53it/s]

evidence split r32 sim=0.7380:   9%|▉         | 11/121 [00:00<00:02, 52.29it/s]

evidence split r32 sim=0.7595:   9%|▉         | 11/121 [00:00<00:02, 52.29it/s]

evidence split r32 sim=0.7767:   9%|▉         | 11/121 [00:00<00:02, 52.29it/s]

evidence split r32 sim=0.7903:   9%|▉         | 11/121 [00:00<00:02, 52.29it/s]

evidence split r32 sim=0.7903:  14%|█▍        | 17/121 [00:00<00:01, 53.92it/s]

evidence split r32 sim=0.8009:  14%|█▍        | 17/121 [00:00<00:01, 53.92it/s]

evidence split r32 sim=0.8096:  14%|█▍        | 17/121 [00:00<00:01, 53.92it/s]

evidence split r32 sim=0.8168:  14%|█▍        | 17/121 [00:00<00:01, 53.92it/s]

evidence split r32 sim=0.8168:  19%|█▉        | 23/121 [00:00<00:01, 54.41it/s]

evidence split r32 sim=0.8229:  19%|█▉        | 23/121 [00:00<00:01, 54.41it/s]

evidence split r32 sim=0.8281:  19%|█▉        | 23/121 [00:00<00:01, 54.41it/s]

evidence split r32 sim=0.8326:  19%|█▉        | 23/121 [00:00<00:01, 54.41it/s]

evidence split r32 sim=0.8326:  24%|██▍       | 29/121 [00:00<00:01, 54.39it/s]

evidence split r32 sim=0.8365:  24%|██▍       | 29/121 [00:00<00:01, 54.39it/s]

evidence split r32 sim=0.8399:  24%|██▍       | 29/121 [00:00<00:01, 54.39it/s]

evidence split r32 sim=0.8429:  24%|██▍       | 29/121 [00:00<00:01, 54.39it/s]

evidence split r32 sim=0.8429:  29%|██▉       | 35/121 [00:00<00:01, 55.67it/s]

evidence split r32 sim=0.8456:  29%|██▉       | 35/121 [00:00<00:01, 55.67it/s]

evidence split r32 sim=0.8480:  29%|██▉       | 35/121 [00:00<00:01, 55.67it/s]

evidence split r32 sim=0.8502:  29%|██▉       | 35/121 [00:00<00:01, 55.67it/s]

evidence split r32 sim=0.8502:  34%|███▍      | 41/121 [00:00<00:01, 56.98it/s]

evidence split r32 sim=0.8522:  34%|███▍      | 41/121 [00:00<00:01, 56.98it/s]

evidence split r32 sim=0.8539:  34%|███▍      | 41/121 [00:00<00:01, 56.98it/s]

evidence split r32 sim=0.8556:  34%|███▍      | 41/121 [00:00<00:01, 56.98it/s]

evidence split r32 sim=0.8556:  39%|███▉      | 47/121 [00:00<00:01, 56.80it/s]

evidence split r32 sim=0.8571:  39%|███▉      | 47/121 [00:00<00:01, 56.80it/s]

evidence split r32 sim=0.8584:  39%|███▉      | 47/121 [00:00<00:01, 56.80it/s]

evidence split r32 sim=0.8597:  39%|███▉      | 47/121 [00:00<00:01, 56.80it/s]

evidence split r32 sim=0.8597:  45%|████▍     | 54/121 [00:00<00:01, 60.13it/s]

evidence split r32 sim=0.8608:  45%|████▍     | 54/121 [00:00<00:01, 60.13it/s]

evidence split r32 sim=0.8619:  45%|████▍     | 54/121 [00:01<00:01, 60.13it/s]

evidence split r32 sim=0.8629:  45%|████▍     | 54/121 [00:01<00:01, 60.13it/s]

evidence split r32 sim=0.8638:  45%|████▍     | 54/121 [00:01<00:01, 60.13it/s]

evidence split r32 sim=0.8638:  50%|█████     | 61/121 [00:01<00:01, 59.23it/s]

evidence split r32 sim=0.8646:  50%|█████     | 61/121 [00:01<00:01, 59.23it/s]

evidence split r32 sim=0.8654:  50%|█████     | 61/121 [00:01<00:01, 59.23it/s]

evidence split r32 sim=0.8661:  50%|█████     | 61/121 [00:01<00:01, 59.23it/s]

evidence split r32 sim=0.8661:  55%|█████▌    | 67/121 [00:01<00:00, 59.26it/s]

evidence split r32 sim=0.8667:  55%|█████▌    | 67/121 [00:01<00:00, 59.26it/s]

evidence split r32 sim=0.8673:  55%|█████▌    | 67/121 [00:01<00:00, 59.26it/s]

evidence split r32 sim=0.8679:  55%|█████▌    | 67/121 [00:01<00:00, 59.26it/s]

evidence split r32 sim=0.8679:  61%|██████    | 74/121 [00:01<00:00, 61.35it/s]

evidence split r32 sim=0.8684:  61%|██████    | 74/121 [00:01<00:00, 61.35it/s]

evidence split r32 sim=0.8689:  61%|██████    | 74/121 [00:01<00:00, 61.35it/s]

evidence split r32 sim=0.8693:  61%|██████    | 74/121 [00:01<00:00, 61.35it/s]

evidence split r32 sim=0.8697:  61%|██████    | 74/121 [00:01<00:00, 61.35it/s]

evidence split r32 sim=0.8697:  67%|██████▋   | 81/121 [00:01<00:00, 58.98it/s]

evidence split r32 sim=0.8700:  67%|██████▋   | 81/121 [00:01<00:00, 58.98it/s]

evidence split r32 sim=0.8703:  67%|██████▋   | 81/121 [00:01<00:00, 58.98it/s]

evidence split r32 sim=0.8706:  67%|██████▋   | 81/121 [00:01<00:00, 58.98it/s]

evidence split r32 sim=0.8706:  73%|███████▎  | 88/121 [00:01<00:00, 60.92it/s]

evidence split r32 sim=0.8709:  73%|███████▎  | 88/121 [00:01<00:00, 60.92it/s]

evidence split r32 sim=0.8711:  73%|███████▎  | 88/121 [00:01<00:00, 60.92it/s]

evidence split r32 sim=0.8713:  73%|███████▎  | 88/121 [00:01<00:00, 60.92it/s]

evidence split r32 sim=0.8715:  73%|███████▎  | 88/121 [00:01<00:00, 60.92it/s]

evidence split r32 sim=0.8715:  79%|███████▊  | 95/121 [00:01<00:00, 60.04it/s]

evidence split r32 sim=0.8716:  79%|███████▊  | 95/121 [00:01<00:00, 60.04it/s]

evidence split r32 sim=0.8718:  79%|███████▊  | 95/121 [00:01<00:00, 60.04it/s]

evidence split r32 sim=0.8719:  79%|███████▊  | 95/121 [00:01<00:00, 60.04it/s]

evidence split r32 sim=0.8719:  84%|████████▍ | 102/121 [00:01<00:00, 61.19it/s]

evidence split r32 sim=0.8720:  84%|████████▍ | 102/121 [00:01<00:00, 61.19it/s]

evidence split r32 sim=0.8720:  84%|████████▍ | 102/121 [00:01<00:00, 61.19it/s]

evidence split r32 sim=0.8721:  84%|████████▍ | 102/121 [00:01<00:00, 61.19it/s]

evidence split r32 sim=0.8722:  84%|████████▍ | 102/121 [00:01<00:00, 61.19it/s]

evidence split r32 sim=0.8722:  90%|█████████ | 109/121 [00:01<00:00, 59.01it/s]

evidence split r32 sim=0.8722:  90%|█████████ | 109/121 [00:01<00:00, 59.01it/s]

evidence split r32 sim=0.8722:  90%|█████████ | 109/121 [00:01<00:00, 59.01it/s]

evidence split r32 sim=0.8722:  90%|█████████ | 109/121 [00:01<00:00, 59.01it/s]

evidence split r32 sim=0.8722:  90%|█████████ | 109/121 [00:01<00:00, 59.01it/s]

evidence split r32 sim=0.8722:  97%|█████████▋| 117/121 [00:01<00:00, 61.50it/s]

evidence split r32 sim=0.8723:  97%|█████████▋| 117/121 [00:02<00:00, 61.50it/s]

evidence split r32 sim=0.8723:  97%|█████████▋| 117/121 [00:02<00:00, 61.50it/s]

evidence split r32 sim=0.8723: 100%|██████████| 121/121 [00:02<00:00, 58.95it/s]

evidence split sparse smooth r32:   0%|          | 0/143 [00:00<?, ?it/s]

evidence split sparse smooth r32 sim=-0.0002:   0%|          | 0/143 [00:00<?, ?it/s]

evidence split sparse smooth r32 sim=0.3172:   0%|          | 0/143 [00:00<?, ?it/s]

evidence split sparse smooth r32 sim=0.5747:   0%|          | 0/143 [00:00<?, ?it/s]

evidence split sparse smooth r32 sim=0.5747:   4%|▍         | 6/143 [00:00<00:02, 59.08it/s]

evidence split sparse smooth r32 sim=0.6724:   4%|▍         | 6/143 [00:00<00:02, 59.08it/s]

evidence split sparse smooth r32 sim=0.7182:   4%|▍         | 6/143 [00:00<00:02, 59.08it/s]

evidence split sparse smooth r32 sim=0.7465:   4%|▍         | 6/143 [00:00<00:02, 59.08it/s]

evidence split sparse smooth r32 sim=0.7465:   8%|▊         | 12/143 [00:00<00:02, 56.99it/s]

evidence split sparse smooth r32 sim=0.7682:   8%|▊         | 12/143 [00:00<00:02, 56.99it/s]

evidence split sparse smooth r32 sim=0.7848:   8%|▊         | 12/143 [00:00<00:02, 56.99it/s]

evidence split sparse smooth r32 sim=0.7976:   8%|▊         | 12/143 [00:00<00:02, 56.99it/s]

evidence split sparse smooth r32 sim=0.7976:  13%|█▎        | 18/143 [00:00<00:02, 56.75it/s]

evidence split sparse smooth r32 sim=0.8077:  13%|█▎        | 18/143 [00:00<00:02, 56.75it/s]

evidence split sparse smooth r32 sim=0.8159:  13%|█▎        | 18/143 [00:00<00:02, 56.75it/s]

evidence split sparse smooth r32 sim=0.8226:  13%|█▎        | 18/143 [00:00<00:02, 56.75it/s]

evidence split sparse smooth r32 sim=0.8226:  17%|█▋        | 24/143 [00:00<00:02, 55.47it/s]

evidence split sparse smooth r32 sim=0.8283:  17%|█▋        | 24/143 [00:00<00:02, 55.47it/s]

evidence split sparse smooth r32 sim=0.8332:  17%|█▋        | 24/143 [00:00<00:02, 55.47it/s]

evidence split sparse smooth r32 sim=0.8374:  17%|█▋        | 24/143 [00:00<00:02, 55.47it/s]

evidence split sparse smooth r32 sim=0.8374:  21%|██        | 30/143 [00:00<00:02, 54.24it/s]

evidence split sparse smooth r32 sim=0.8410:  21%|██        | 30/143 [00:00<00:02, 54.24it/s]

evidence split sparse smooth r32 sim=0.8442:  21%|██        | 30/143 [00:00<00:02, 54.24it/s]

evidence split sparse smooth r32 sim=0.8470:  21%|██        | 30/143 [00:00<00:02, 54.24it/s]

evidence split sparse smooth r32 sim=0.8470:  25%|██▌       | 36/143 [00:00<00:01, 53.77it/s]

evidence split sparse smooth r32 sim=0.8496:  25%|██▌       | 36/143 [00:00<00:01, 53.77it/s]

evidence split sparse smooth r32 sim=0.8518:  25%|██▌       | 36/143 [00:00<00:01, 53.77it/s]

evidence split sparse smooth r32 sim=0.8539:  25%|██▌       | 36/143 [00:00<00:01, 53.77it/s]

evidence split sparse smooth r32 sim=0.8539:  29%|██▉       | 42/143 [00:00<00:01, 53.17it/s]

evidence split sparse smooth r32 sim=0.8557:  29%|██▉       | 42/143 [00:00<00:01, 53.17it/s]

evidence split sparse smooth r32 sim=0.8575:  29%|██▉       | 42/143 [00:00<00:01, 53.17it/s]

evidence split sparse smooth r32 sim=0.8590:  29%|██▉       | 42/143 [00:00<00:01, 53.17it/s]

evidence split sparse smooth r32 sim=0.8590:  34%|███▎      | 48/143 [00:00<00:01, 52.82it/s]

evidence split sparse smooth r32 sim=0.8605:  34%|███▎      | 48/143 [00:00<00:01, 52.82it/s]

evidence split sparse smooth r32 sim=0.8618:  34%|███▎      | 48/143 [00:00<00:01, 52.82it/s]

evidence split sparse smooth r32 sim=0.8630:  34%|███▎      | 48/143 [00:00<00:01, 52.82it/s]

evidence split sparse smooth r32 sim=0.8630:  38%|███▊      | 54/143 [00:01<00:01, 52.41it/s]

evidence split sparse smooth r32 sim=0.8641:  38%|███▊      | 54/143 [00:01<00:01, 52.41it/s]

evidence split sparse smooth r32 sim=0.8651:  38%|███▊      | 54/143 [00:01<00:01, 52.41it/s]

evidence split sparse smooth r32 sim=0.8661:  38%|███▊      | 54/143 [00:01<00:01, 52.41it/s]

evidence split sparse smooth r32 sim=0.8661:  42%|████▏     | 60/143 [00:01<00:01, 52.19it/s]

evidence split sparse smooth r32 sim=0.8669:  42%|████▏     | 60/143 [00:01<00:01, 52.19it/s]

evidence split sparse smooth r32 sim=0.8677:  42%|████▏     | 60/143 [00:01<00:01, 52.19it/s]

evidence split sparse smooth r32 sim=0.8685:  42%|████▏     | 60/143 [00:01<00:01, 52.19it/s]

evidence split sparse smooth r32 sim=0.8685:  46%|████▌     | 66/143 [00:01<00:01, 51.22it/s]

evidence split sparse smooth r32 sim=0.8692:  46%|████▌     | 66/143 [00:01<00:01, 51.22it/s]

evidence split sparse smooth r32 sim=0.8698:  46%|████▌     | 66/143 [00:01<00:01, 51.22it/s]

evidence split sparse smooth r32 sim=0.8704:  46%|████▌     | 66/143 [00:01<00:01, 51.22it/s]

evidence split sparse smooth r32 sim=0.8704:  50%|█████     | 72/143 [00:01<00:01, 50.52it/s]

evidence split sparse smooth r32 sim=0.8709:  50%|█████     | 72/143 [00:01<00:01, 50.52it/s]

evidence split sparse smooth r32 sim=0.8715:  50%|█████     | 72/143 [00:01<00:01, 50.52it/s]

evidence split sparse smooth r32 sim=0.8719:  50%|█████     | 72/143 [00:01<00:01, 50.52it/s]

evidence split sparse smooth r32 sim=0.8719:  55%|█████▍    | 78/143 [00:01<00:01, 50.07it/s]

evidence split sparse smooth r32 sim=0.8724:  55%|█████▍    | 78/143 [00:01<00:01, 50.07it/s]

evidence split sparse smooth r32 sim=0.8728:  55%|█████▍    | 78/143 [00:01<00:01, 50.07it/s]

evidence split sparse smooth r32 sim=0.8732:  55%|█████▍    | 78/143 [00:01<00:01, 50.07it/s]

evidence split sparse smooth r32 sim=0.8732:  59%|█████▊    | 84/143 [00:01<00:01, 50.13it/s]

evidence split sparse smooth r32 sim=0.8736:  59%|█████▊    | 84/143 [00:01<00:01, 50.13it/s]

evidence split sparse smooth r32 sim=0.8739:  59%|█████▊    | 84/143 [00:01<00:01, 50.13it/s]

evidence split sparse smooth r32 sim=0.8742:  59%|█████▊    | 84/143 [00:01<00:01, 50.13it/s]

evidence split sparse smooth r32 sim=0.8742:  63%|██████▎   | 90/143 [00:01<00:01, 49.51it/s]

evidence split sparse smooth r32 sim=0.8745:  63%|██████▎   | 90/143 [00:01<00:01, 49.51it/s]

evidence split sparse smooth r32 sim=0.8748:  63%|██████▎   | 90/143 [00:01<00:01, 49.51it/s]

evidence split sparse smooth r32 sim=0.8750:  63%|██████▎   | 90/143 [00:01<00:01, 49.51it/s]

evidence split sparse smooth r32 sim=0.8750:  66%|██████▋   | 95/143 [00:01<00:00, 48.04it/s]

evidence split sparse smooth r32 sim=0.8752:  66%|██████▋   | 95/143 [00:01<00:00, 48.04it/s]

evidence split sparse smooth r32 sim=0.8755:  66%|██████▋   | 95/143 [00:01<00:00, 48.04it/s]

evidence split sparse smooth r32 sim=0.8757:  66%|██████▋   | 95/143 [00:01<00:00, 48.04it/s]

evidence split sparse smooth r32 sim=0.8757:  71%|███████   | 101/143 [00:01<00:00, 47.85it/s]

evidence split sparse smooth r32 sim=0.8758:  71%|███████   | 101/143 [00:02<00:00, 47.85it/s]

evidence split sparse smooth r32 sim=0.8760:  71%|███████   | 101/143 [00:02<00:00, 47.85it/s]

evidence split sparse smooth r32 sim=0.8761:  71%|███████   | 101/143 [00:02<00:00, 47.85it/s]

evidence split sparse smooth r32 sim=0.8761:  75%|███████▍  | 107/143 [00:02<00:00, 47.53it/s]

evidence split sparse smooth r32 sim=0.8763:  75%|███████▍  | 107/143 [00:02<00:00, 47.53it/s]

evidence split sparse smooth r32 sim=0.8764:  75%|███████▍  | 107/143 [00:02<00:00, 47.53it/s]

evidence split sparse smooth r32 sim=0.8765:  75%|███████▍  | 107/143 [00:02<00:00, 47.53it/s]

evidence split sparse smooth r32 sim=0.8765:  79%|███████▉  | 113/143 [00:02<00:00, 47.54it/s]

evidence split sparse smooth r32 sim=0.8766:  79%|███████▉  | 113/143 [00:02<00:00, 47.54it/s]

evidence split sparse smooth r32 sim=0.8767:  79%|███████▉  | 113/143 [00:02<00:00, 47.54it/s]

evidence split sparse smooth r32 sim=0.8767:  79%|███████▉  | 113/143 [00:02<00:00, 47.54it/s]

evidence split sparse smooth r32 sim=0.8767:  83%|████████▎ | 119/143 [00:02<00:00, 47.58it/s]

evidence split sparse smooth r32 sim=0.8768:  83%|████████▎ | 119/143 [00:02<00:00, 47.58it/s]

evidence split sparse smooth r32 sim=0.8769:  83%|████████▎ | 119/143 [00:02<00:00, 47.58it/s]

evidence split sparse smooth r32 sim=0.8769:  83%|████████▎ | 119/143 [00:02<00:00, 47.58it/s]

evidence split sparse smooth r32 sim=0.8769:  87%|████████▋ | 125/143 [00:02<00:00, 47.52it/s]

evidence split sparse smooth r32 sim=0.8769:  87%|████████▋ | 125/143 [00:02<00:00, 47.52it/s]

evidence split sparse smooth r32 sim=0.8770:  87%|████████▋ | 125/143 [00:02<00:00, 47.52it/s]

evidence split sparse smooth r32 sim=0.8770:  87%|████████▋ | 125/143 [00:02<00:00, 47.52it/s]

evidence split sparse smooth r32 sim=0.8770:  92%|█████████▏| 131/143 [00:02<00:00, 47.74it/s]

evidence split sparse smooth r32 sim=0.8770:  92%|█████████▏| 131/143 [00:02<00:00, 47.74it/s]

evidence split sparse smooth r32 sim=0.8770:  92%|█████████▏| 131/143 [00:02<00:00, 47.74it/s]

evidence split sparse smooth r32 sim=0.8770:  92%|█████████▏| 131/143 [00:02<00:00, 47.74it/s]

evidence split sparse smooth r32 sim=0.8770:  96%|█████████▌| 137/143 [00:02<00:00, 48.58it/s]

evidence split sparse smooth r32 sim=0.8770:  96%|█████████▌| 137/143 [00:02<00:00, 48.58it/s]

evidence split sparse smooth r32 sim=0.8770:  96%|█████████▌| 137/143 [00:02<00:00, 48.58it/s]

evidence split sparse smooth r32 sim=0.8770:  96%|█████████▌| 137/143 [00:02<00:00, 48.58it/s]

evidence split sparse smooth r32 sim=0.8770: 100%|██████████| 143/143 [00:02<00:00, 49.38it/s]

evidence split sparse smooth r32 sim=0.8770: 100%|██████████| 143/143 [00:02<00:00, 50.42it/s]

nonnegative strokes r48:   0%|          | 0/143 [00:00<?, ?it/s]

nonnegative strokes r48 sim=-0.0016:   0%|          | 0/143 [00:00<?, ?it/s]

nonnegative strokes r48 sim=-0.0016:   1%|▏         | 2/143 [00:00<00:07, 18.43it/s]

nonnegative strokes r48 sim=0.0191:   1%|▏         | 2/143 [00:00<00:07, 18.43it/s]

nonnegative strokes r48 sim=0.0217:   1%|▏         | 2/143 [00:00<00:07, 18.43it/s]

nonnegative strokes r48 sim=0.0228:   1%|▏         | 2/143 [00:00<00:07, 18.43it/s]

nonnegative strokes r48 sim=0.0228:   5%|▍         | 7/143 [00:00<00:03, 35.39it/s]

nonnegative strokes r48 sim=0.0238:   5%|▍         | 7/143 [00:00<00:03, 35.39it/s]

nonnegative strokes r48 sim=0.0248:   5%|▍         | 7/143 [00:00<00:03, 35.39it/s]

nonnegative strokes r48 sim=0.0260:   5%|▍         | 7/143 [00:00<00:03, 35.39it/s]

nonnegative strokes r48 sim=0.0260:   9%|▉         | 13/143 [00:00<00:02, 43.78it/s]

nonnegative strokes r48 sim=0.0273:   9%|▉         | 13/143 [00:00<00:02, 43.78it/s]

nonnegative strokes r48 sim=0.0288:   9%|▉         | 13/143 [00:00<00:02, 43.78it/s]

nonnegative strokes r48 sim=0.0304:   9%|▉         | 13/143 [00:00<00:02, 43.78it/s]

nonnegative strokes r48 sim=0.0304:  13%|█▎        | 19/143 [00:00<00:02, 48.87it/s]

nonnegative strokes r48 sim=0.0323:  13%|█▎        | 19/143 [00:00<00:02, 48.87it/s]

nonnegative strokes r48 sim=0.0344:  13%|█▎        | 19/143 [00:00<00:02, 48.87it/s]

nonnegative strokes r48 sim=0.0367:  13%|█▎        | 19/143 [00:00<00:02, 48.87it/s]

nonnegative strokes r48 sim=0.0367:  17%|█▋        | 25/143 [00:00<00:02, 51.15it/s]

nonnegative strokes r48 sim=0.0393:  17%|█▋        | 25/143 [00:00<00:02, 51.15it/s]

nonnegative strokes r48 sim=0.0421:  17%|█▋        | 25/143 [00:00<00:02, 51.15it/s]

nonnegative strokes r48 sim=0.0451:  17%|█▋        | 25/143 [00:00<00:02, 51.15it/s]

nonnegative strokes r48 sim=0.0451:  22%|██▏       | 31/143 [00:00<00:02, 52.30it/s]

nonnegative strokes r48 sim=0.0483:  22%|██▏       | 31/143 [00:00<00:02, 52.30it/s]

nonnegative strokes r48 sim=0.0515:  22%|██▏       | 31/143 [00:00<00:02, 52.30it/s]

nonnegative strokes r48 sim=0.0547:  22%|██▏       | 31/143 [00:00<00:02, 52.30it/s]

nonnegative strokes r48 sim=0.0547:  26%|██▌       | 37/143 [00:00<00:02, 52.96it/s]

nonnegative strokes r48 sim=0.0579:  26%|██▌       | 37/143 [00:00<00:02, 52.96it/s]

nonnegative strokes r48 sim=0.0609:  26%|██▌       | 37/143 [00:00<00:02, 52.96it/s]

nonnegative strokes r48 sim=0.0637:  26%|██▌       | 37/143 [00:00<00:02, 52.96it/s]

nonnegative strokes r48 sim=0.0637:  30%|███       | 43/143 [00:00<00:01, 53.52it/s]

nonnegative strokes r48 sim=0.0662:  30%|███       | 43/143 [00:00<00:01, 53.52it/s]

nonnegative strokes r48 sim=0.0685:  30%|███       | 43/143 [00:00<00:01, 53.52it/s]

nonnegative strokes r48 sim=0.0706:  30%|███       | 43/143 [00:00<00:01, 53.52it/s]

nonnegative strokes r48 sim=0.0706:  34%|███▍      | 49/143 [00:00<00:01, 54.19it/s]

nonnegative strokes r48 sim=0.0723:  34%|███▍      | 49/143 [00:01<00:01, 54.19it/s]

nonnegative strokes r48 sim=0.0739:  34%|███▍      | 49/143 [00:01<00:01, 54.19it/s]

nonnegative strokes r48 sim=0.0753:  34%|███▍      | 49/143 [00:01<00:01, 54.19it/s]

nonnegative strokes r48 sim=0.0753:  38%|███▊      | 55/143 [00:01<00:01, 54.32it/s]

nonnegative strokes r48 sim=0.0765:  38%|███▊      | 55/143 [00:01<00:01, 54.32it/s]

nonnegative strokes r48 sim=0.0776:  38%|███▊      | 55/143 [00:01<00:01, 54.32it/s]

nonnegative strokes r48 sim=0.0785:  38%|███▊      | 55/143 [00:01<00:01, 54.32it/s]

nonnegative strokes r48 sim=0.0785:  43%|████▎     | 61/143 [00:01<00:01, 54.39it/s]

nonnegative strokes r48 sim=0.0794:  43%|████▎     | 61/143 [00:01<00:01, 54.39it/s]

nonnegative strokes r48 sim=0.0802:  43%|████▎     | 61/143 [00:01<00:01, 54.39it/s]

nonnegative strokes r48 sim=0.0809:  43%|████▎     | 61/143 [00:01<00:01, 54.39it/s]

nonnegative strokes r48 sim=0.0809:  47%|████▋     | 67/143 [00:01<00:01, 54.36it/s]

nonnegative strokes r48 sim=0.0816:  47%|████▋     | 67/143 [00:01<00:01, 54.36it/s]

nonnegative strokes r48 sim=0.0822:  47%|████▋     | 67/143 [00:01<00:01, 54.36it/s]

nonnegative strokes r48 sim=0.0827:  47%|████▋     | 67/143 [00:01<00:01, 54.36it/s]

nonnegative strokes r48 sim=0.0827:  51%|█████     | 73/143 [00:01<00:01, 55.26it/s]

nonnegative strokes r48 sim=0.0832:  51%|█████     | 73/143 [00:01<00:01, 55.26it/s]

nonnegative strokes r48 sim=0.0836:  51%|█████     | 73/143 [00:01<00:01, 55.26it/s]

nonnegative strokes r48 sim=0.0840:  51%|█████     | 73/143 [00:01<00:01, 55.26it/s]

nonnegative strokes r48 sim=0.0840:  55%|█████▌    | 79/143 [00:01<00:01, 55.81it/s]

nonnegative strokes r48 sim=0.0843:  55%|█████▌    | 79/143 [00:01<00:01, 55.81it/s]

nonnegative strokes r48 sim=0.0846:  55%|█████▌    | 79/143 [00:01<00:01, 55.81it/s]

nonnegative strokes r48 sim=0.0849:  55%|█████▌    | 79/143 [00:01<00:01, 55.81it/s]

nonnegative strokes r48 sim=0.0849:  59%|█████▉    | 85/143 [00:01<00:01, 55.05it/s]

nonnegative strokes r48 sim=0.0851:  59%|█████▉    | 85/143 [00:01<00:01, 55.05it/s]

nonnegative strokes r48 sim=0.0854:  59%|█████▉    | 85/143 [00:01<00:01, 55.05it/s]

nonnegative strokes r48 sim=0.0856:  59%|█████▉    | 85/143 [00:01<00:01, 55.05it/s]

nonnegative strokes r48 sim=0.0856:  64%|██████▎   | 91/143 [00:01<00:00, 55.14it/s]

nonnegative strokes r48 sim=0.0858:  64%|██████▎   | 91/143 [00:01<00:00, 55.14it/s]

nonnegative strokes r48 sim=0.0859:  64%|██████▎   | 91/143 [00:01<00:00, 55.14it/s]

nonnegative strokes r48 sim=0.0861:  64%|██████▎   | 91/143 [00:01<00:00, 55.14it/s]

nonnegative strokes r48 sim=0.0861:  68%|██████▊   | 97/143 [00:01<00:00, 55.47it/s]

nonnegative strokes r48 sim=0.0862:  68%|██████▊   | 97/143 [00:01<00:00, 55.47it/s]

nonnegative strokes r48 sim=0.0864:  68%|██████▊   | 97/143 [00:01<00:00, 55.47it/s]

nonnegative strokes r48 sim=0.0865:  68%|██████▊   | 97/143 [00:01<00:00, 55.47it/s]

nonnegative strokes r48 sim=0.0865:  73%|███████▎  | 104/143 [00:01<00:00, 58.33it/s]

nonnegative strokes r48 sim=0.0866:  73%|███████▎  | 104/143 [00:01<00:00, 58.33it/s]

nonnegative strokes r48 sim=0.0867:  73%|███████▎  | 104/143 [00:02<00:00, 58.33it/s]

nonnegative strokes r48 sim=0.0867:  73%|███████▎  | 104/143 [00:02<00:00, 58.33it/s]

nonnegative strokes r48 sim=0.0867:  77%|███████▋  | 110/143 [00:02<00:00, 58.31it/s]

nonnegative strokes r48 sim=0.0868:  77%|███████▋  | 110/143 [00:02<00:00, 58.31it/s]

nonnegative strokes r48 sim=0.0868:  77%|███████▋  | 110/143 [00:02<00:00, 58.31it/s]

nonnegative strokes r48 sim=0.0869:  77%|███████▋  | 110/143 [00:02<00:00, 58.31it/s]

nonnegative strokes r48 sim=0.0869:  81%|████████  | 116/143 [00:02<00:00, 57.53it/s]

nonnegative strokes r48 sim=0.0869:  81%|████████  | 116/143 [00:02<00:00, 57.53it/s]

nonnegative strokes r48 sim=0.0870:  81%|████████  | 116/143 [00:02<00:00, 57.53it/s]

nonnegative strokes r48 sim=0.0870:  81%|████████  | 116/143 [00:02<00:00, 57.53it/s]

nonnegative strokes r48 sim=0.0870:  85%|████████▌ | 122/143 [00:02<00:00, 56.77it/s]

nonnegative strokes r48 sim=0.0870:  85%|████████▌ | 122/143 [00:02<00:00, 56.77it/s]

nonnegative strokes r48 sim=0.0871:  85%|████████▌ | 122/143 [00:02<00:00, 56.77it/s]

nonnegative strokes r48 sim=0.0871:  85%|████████▌ | 122/143 [00:02<00:00, 56.77it/s]

nonnegative strokes r48 sim=0.0871:  90%|████████▉ | 128/143 [00:02<00:00, 56.51it/s]

nonnegative strokes r48 sim=0.0871:  90%|████████▉ | 128/143 [00:02<00:00, 56.51it/s]

nonnegative strokes r48 sim=0.0871:  90%|████████▉ | 128/143 [00:02<00:00, 56.51it/s]

nonnegative strokes r48 sim=0.0871:  90%|████████▉ | 128/143 [00:02<00:00, 56.51it/s]

nonnegative strokes r48 sim=0.0871:  94%|█████████▎| 134/143 [00:02<00:00, 56.91it/s]

nonnegative strokes r48 sim=0.0871:  94%|█████████▎| 134/143 [00:02<00:00, 56.91it/s]

nonnegative strokes r48 sim=0.0871:  94%|█████████▎| 134/143 [00:02<00:00, 56.91it/s]

nonnegative strokes r48 sim=0.0871:  94%|█████████▎| 134/143 [00:02<00:00, 56.91it/s]

nonnegative strokes r48 sim=0.0871:  98%|█████████▊| 140/143 [00:02<00:00, 56.85it/s]

nonnegative strokes r48 sim=0.0871:  98%|█████████▊| 140/143 [00:02<00:00, 56.85it/s]

nonnegative strokes r48 sim=0.0871:  98%|█████████▊| 140/143 [00:02<00:00, 56.85it/s]

nonnegative strokes r48 sim=0.0871: 100%|██████████| 143/143 [00:02<00:00, 53.93it/s]

,name,similarity,test_acc,pattern_gini,locality_7x7,class_selectivity,top_sigma_frac
5,evidence split sparse smooth r32,0.877034,0.9548,0.440257,0.254946,0.120680,0.306341
4,evidence split r32,0.872256,0.9611,0.434809,0.237860,0.109408,0.290891
1,cp r32 symmetry-soft,0.860983,0.9511,0.437123,0.238074,0.103718,0.299290
0,provided Sparse r32,0.858908,0.9492,0.440377,0.264228,0.106274,0.295426
3,symmetric sparse smooth r32,0.787751,0.9316,0.222727,0.138692,0.108916,0.300652
2,symmetric r32,0.778788,0.8867,0.221623,0.139064,0.116112,0.287478
6,nonnegative strokes r48,0.087126,0.4322,0.010952,0.063500,0.103726,0.277420

In [13]:
# Show training curves for the non-baseline variants.
for name, history in histories.items():
    plot_history(history, name)

## Visual Comparison Of All Variants

In [14]:
for name, factor in trained.items():
    if name == "provided Sparse r64":
        plus, minus, down, sigma = factor.decompose()
        fig = component_figure(plus.cpu(), minus.cpu(), down.cpu(), sigma.cpu(), k=10, title=name)
        save_fig(fig, "components_provided_sparse_r64")
    else:
        plot_factor_components(factor, name, k=10)

## Eigenvector-Seeded Shared Dictionary

This is a bridge back to tutorial 1. We take the largest-magnitude per-class eigenvectors and use them as a global initialization for a symmetric shared dictionary, then fine-tune the shared decomposition. If this works, it suggests the tensor dictionary is compressing per-class eigenfeatures into reusable strokes.

In [15]:
@torch.no_grad()
def eigen_seeded_symmetric(target=B, rank=64):
    # MPS currently lacks linalg.eigh; this one-time initialization is fine on CPU.
    target_cpu = target.detach().cpu()
    vals, vecs = torch.linalg.eigh(target_cpu)
    flat = vals.abs().flatten()
    idx = flat.topk(rank).indices
    cls = idx // vals.shape[1]
    comp = idx % vals.shape[1]

    seed_vectors = torch.stack([vecs[c, :, k] for c, k in zip(cls.tolist(), comp.tolist())], dim=1)
    seed_down = torch.zeros(10, rank)
    for r, (c, k) in enumerate(zip(cls.tolist(), comp.tolist())):
        seed_down[c, r] = vals[c, k]

    m = SymmetricFactorModel(rank=rank).to(target.device)
    m.raw_v.copy_(seed_vectors.to(target.device))
    m.raw_down.copy_(seed_down.to(target.device))
    return m

eigen_model = eigen_seeded_symmetric(B, rank=BASE_RANK)
eigen_model, eigen_history = fit_factor_model(
    eigen_model,
    f"eigen seeded symmetric sparse smooth r{BASE_RANK}",
    steps=int(450 * VARIANT_STEP_SCALE),
    lr=0.02,
    reg=RegConfig(l1=1e-4, tv=1e-3, d_l1=1e-4, duplicate=1e-3),
    seed=None,
)
eigen_name = f"eigen seeded symmetric sparse smooth r{BASE_RANK}"
trained[eigen_name] = eigen_model
histories[eigen_name] = eigen_history
rows.append(metric_dict(eigen_name, eigen_model))
results = show_table(rows, sort_by="similarity")
plot_factor_components(eigen_model, eigen_name, k=10)

eigen seeded symmetric sparse smooth r32:   0%|          | 0/99 [00:00<?, ?it/s]

eigen seeded symmetric sparse smooth r32 sim=0.6447:   0%|          | 0/99 [00:00<?, ?it/s]

eigen seeded symmetric sparse smooth r32 sim=0.5352:   0%|          | 0/99 [00:00<?, ?it/s]

eigen seeded symmetric sparse smooth r32 sim=0.6492:   0%|          | 0/99 [00:00<?, ?it/s]

eigen seeded symmetric sparse smooth r32 sim=0.6426:   0%|          | 0/99 [00:00<?, ?it/s]

eigen seeded symmetric sparse smooth r32 sim=0.6397:   0%|          | 0/99 [00:00<?, ?it/s]

eigen seeded symmetric sparse smooth r32 sim=0.6578:   0%|          | 0/99 [00:00<?, ?it/s]

eigen seeded symmetric sparse smooth r32 sim=0.6792:   0%|          | 0/99 [00:00<?, ?it/s]

eigen seeded symmetric sparse smooth r32 sim=0.6792:   7%|▋         | 7/99 [00:00<00:01, 62.53it/s]

eigen seeded symmetric sparse smooth r32 sim=0.6948:   7%|▋         | 7/99 [00:00<00:01, 62.53it/s]

eigen seeded symmetric sparse smooth r32 sim=0.7040:   7%|▋         | 7/99 [00:00<00:01, 62.53it/s]

eigen seeded symmetric sparse smooth r32 sim=0.7099:   7%|▋         | 7/99 [00:00<00:01, 62.53it/s]

eigen seeded symmetric sparse smooth r32 sim=0.7152:   7%|▋         | 7/99 [00:00<00:01, 62.53it/s]

eigen seeded symmetric sparse smooth r32 sim=0.7213:   7%|▋         | 7/99 [00:00<00:01, 62.53it/s]

eigen seeded symmetric sparse smooth r32 sim=0.7280:   7%|▋         | 7/99 [00:00<00:01, 62.53it/s]

eigen seeded symmetric sparse smooth r32 sim=0.7345:   7%|▋         | 7/99 [00:00<00:01, 62.53it/s]

eigen seeded symmetric sparse smooth r32 sim=0.7345:  14%|█▍        | 14/99 [00:00<00:01, 64.89it/s]

eigen seeded symmetric sparse smooth r32 sim=0.7402:  14%|█▍        | 14/99 [00:00<00:01, 64.89it/s]

eigen seeded symmetric sparse smooth r32 sim=0.7449:  14%|█▍        | 14/99 [00:00<00:01, 64.89it/s]

eigen seeded symmetric sparse smooth r32 sim=0.7487:  14%|█▍        | 14/99 [00:00<00:01, 64.89it/s]

eigen seeded symmetric sparse smooth r32 sim=0.7520:  14%|█▍        | 14/99 [00:00<00:01, 64.89it/s]

eigen seeded symmetric sparse smooth r32 sim=0.7549:  14%|█▍        | 14/99 [00:00<00:01, 64.89it/s]

eigen seeded symmetric sparse smooth r32 sim=0.7577:  14%|█▍        | 14/99 [00:00<00:01, 64.89it/s]

eigen seeded symmetric sparse smooth r32 sim=0.7604:  14%|█▍        | 14/99 [00:00<00:01, 64.89it/s]

eigen seeded symmetric sparse smooth r32 sim=0.7604:  21%|██        | 21/99 [00:00<00:01, 51.43it/s]

eigen seeded symmetric sparse smooth r32 sim=0.7629:  21%|██        | 21/99 [00:00<00:01, 51.43it/s]

eigen seeded symmetric sparse smooth r32 sim=0.7654:  21%|██        | 21/99 [00:00<00:01, 51.43it/s]

eigen seeded symmetric sparse smooth r32 sim=0.7676:  21%|██        | 21/99 [00:00<00:01, 51.43it/s]

eigen seeded symmetric sparse smooth r32 sim=0.7697:  21%|██        | 21/99 [00:00<00:01, 51.43it/s]

eigen seeded symmetric sparse smooth r32 sim=0.7717:  21%|██        | 21/99 [00:00<00:01, 51.43it/s]

eigen seeded symmetric sparse smooth r32 sim=0.7735:  21%|██        | 21/99 [00:00<00:01, 51.43it/s]

eigen seeded symmetric sparse smooth r32 sim=0.7735:  27%|██▋       | 27/99 [00:00<00:01, 45.74it/s]

eigen seeded symmetric sparse smooth r32 sim=0.7752:  27%|██▋       | 27/99 [00:00<00:01, 45.74it/s]

eigen seeded symmetric sparse smooth r32 sim=0.7769:  27%|██▋       | 27/99 [00:00<00:01, 45.74it/s]

eigen seeded symmetric sparse smooth r32 sim=0.7784:  27%|██▋       | 27/99 [00:00<00:01, 45.74it/s]

eigen seeded symmetric sparse smooth r32 sim=0.7799:  27%|██▋       | 27/99 [00:00<00:01, 45.74it/s]

eigen seeded symmetric sparse smooth r32 sim=0.7812:  27%|██▋       | 27/99 [00:00<00:01, 45.74it/s]

eigen seeded symmetric sparse smooth r32 sim=0.7812:  32%|███▏      | 32/99 [00:00<00:01, 46.67it/s]

eigen seeded symmetric sparse smooth r32 sim=0.7825:  32%|███▏      | 32/99 [00:00<00:01, 46.67it/s]

eigen seeded symmetric sparse smooth r32 sim=0.7837:  32%|███▏      | 32/99 [00:00<00:01, 46.67it/s]

eigen seeded symmetric sparse smooth r32 sim=0.7848:  32%|███▏      | 32/99 [00:00<00:01, 46.67it/s]

eigen seeded symmetric sparse smooth r32 sim=0.7859:  32%|███▏      | 32/99 [00:00<00:01, 46.67it/s]

eigen seeded symmetric sparse smooth r32 sim=0.7869:  32%|███▏      | 32/99 [00:00<00:01, 46.67it/s]

eigen seeded symmetric sparse smooth r32 sim=0.7878:  32%|███▏      | 32/99 [00:00<00:01, 46.67it/s]

eigen seeded symmetric sparse smooth r32 sim=0.7878:  38%|███▊      | 38/99 [00:00<00:01, 47.89it/s]

eigen seeded symmetric sparse smooth r32 sim=0.7887:  38%|███▊      | 38/99 [00:00<00:01, 47.89it/s]

eigen seeded symmetric sparse smooth r32 sim=0.7895:  38%|███▊      | 38/99 [00:00<00:01, 47.89it/s]

eigen seeded symmetric sparse smooth r32 sim=0.7903:  38%|███▊      | 38/99 [00:00<00:01, 47.89it/s]

eigen seeded symmetric sparse smooth r32 sim=0.7911:  38%|███▊      | 38/99 [00:00<00:01, 47.89it/s]

eigen seeded symmetric sparse smooth r32 sim=0.7918:  38%|███▊      | 38/99 [00:00<00:01, 47.89it/s]

eigen seeded symmetric sparse smooth r32 sim=0.7918:  43%|████▎     | 43/99 [00:00<00:01, 48.30it/s]

eigen seeded symmetric sparse smooth r32 sim=0.7925:  43%|████▎     | 43/99 [00:00<00:01, 48.30it/s]

eigen seeded symmetric sparse smooth r32 sim=0.7931:  43%|████▎     | 43/99 [00:00<00:01, 48.30it/s]

eigen seeded symmetric sparse smooth r32 sim=0.7937:  43%|████▎     | 43/99 [00:00<00:01, 48.30it/s]

eigen seeded symmetric sparse smooth r32 sim=0.7943:  43%|████▎     | 43/99 [00:00<00:01, 48.30it/s]

eigen seeded symmetric sparse smooth r32 sim=0.7949:  43%|████▎     | 43/99 [00:00<00:01, 48.30it/s]

eigen seeded symmetric sparse smooth r32 sim=0.7949:  48%|████▊     | 48/99 [00:00<00:01, 48.17it/s]

eigen seeded symmetric sparse smooth r32 sim=0.7954:  48%|████▊     | 48/99 [00:00<00:01, 48.17it/s]

eigen seeded symmetric sparse smooth r32 sim=0.7959:  48%|████▊     | 48/99 [00:01<00:01, 48.17it/s]

eigen seeded symmetric sparse smooth r32 sim=0.7963:  48%|████▊     | 48/99 [00:01<00:01, 48.17it/s]

eigen seeded symmetric sparse smooth r32 sim=0.7968:  48%|████▊     | 48/99 [00:01<00:01, 48.17it/s]

eigen seeded symmetric sparse smooth r32 sim=0.7972:  48%|████▊     | 48/99 [00:01<00:01, 48.17it/s]

eigen seeded symmetric sparse smooth r32 sim=0.7972:  54%|█████▎    | 53/99 [00:01<00:00, 47.25it/s]

eigen seeded symmetric sparse smooth r32 sim=0.7976:  54%|█████▎    | 53/99 [00:01<00:00, 47.25it/s]

eigen seeded symmetric sparse smooth r32 sim=0.7979:  54%|█████▎    | 53/99 [00:01<00:00, 47.25it/s]

eigen seeded symmetric sparse smooth r32 sim=0.7983:  54%|█████▎    | 53/99 [00:01<00:00, 47.25it/s]

eigen seeded symmetric sparse smooth r32 sim=0.7986:  54%|█████▎    | 53/99 [00:01<00:00, 47.25it/s]

eigen seeded symmetric sparse smooth r32 sim=0.7989:  54%|█████▎    | 53/99 [00:01<00:00, 47.25it/s]

eigen seeded symmetric sparse smooth r32 sim=0.7992:  54%|█████▎    | 53/99 [00:01<00:00, 47.25it/s]

eigen seeded symmetric sparse smooth r32 sim=0.7992:  60%|█████▉    | 59/99 [00:01<00:00, 48.76it/s]

eigen seeded symmetric sparse smooth r32 sim=0.7994:  60%|█████▉    | 59/99 [00:01<00:00, 48.76it/s]

eigen seeded symmetric sparse smooth r32 sim=0.7997:  60%|█████▉    | 59/99 [00:01<00:00, 48.76it/s]

eigen seeded symmetric sparse smooth r32 sim=0.7999:  60%|█████▉    | 59/99 [00:01<00:00, 48.76it/s]

eigen seeded symmetric sparse smooth r32 sim=0.8001:  60%|█████▉    | 59/99 [00:01<00:00, 48.76it/s]

eigen seeded symmetric sparse smooth r32 sim=0.8003:  60%|█████▉    | 59/99 [00:01<00:00, 48.76it/s]

eigen seeded symmetric sparse smooth r32 sim=0.8005:  60%|█████▉    | 59/99 [00:01<00:00, 48.76it/s]

eigen seeded symmetric sparse smooth r32 sim=0.8005:  66%|██████▌   | 65/99 [00:01<00:00, 50.25it/s]

eigen seeded symmetric sparse smooth r32 sim=0.8007:  66%|██████▌   | 65/99 [00:01<00:00, 50.25it/s]

eigen seeded symmetric sparse smooth r32 sim=0.8009:  66%|██████▌   | 65/99 [00:01<00:00, 50.25it/s]

eigen seeded symmetric sparse smooth r32 sim=0.8010:  66%|██████▌   | 65/99 [00:01<00:00, 50.25it/s]

eigen seeded symmetric sparse smooth r32 sim=0.8012:  66%|██████▌   | 65/99 [00:01<00:00, 50.25it/s]

eigen seeded symmetric sparse smooth r32 sim=0.8013:  66%|██████▌   | 65/99 [00:01<00:00, 50.25it/s]

eigen seeded symmetric sparse smooth r32 sim=0.8014:  66%|██████▌   | 65/99 [00:01<00:00, 50.25it/s]

eigen seeded symmetric sparse smooth r32 sim=0.8014:  72%|███████▏  | 71/99 [00:01<00:00, 51.03it/s]

eigen seeded symmetric sparse smooth r32 sim=0.8015:  72%|███████▏  | 71/99 [00:01<00:00, 51.03it/s]

eigen seeded symmetric sparse smooth r32 sim=0.8016:  72%|███████▏  | 71/99 [00:01<00:00, 51.03it/s]

eigen seeded symmetric sparse smooth r32 sim=0.8017:  72%|███████▏  | 71/99 [00:01<00:00, 51.03it/s]

eigen seeded symmetric sparse smooth r32 sim=0.8018:  72%|███████▏  | 71/99 [00:01<00:00, 51.03it/s]

eigen seeded symmetric sparse smooth r32 sim=0.8019:  72%|███████▏  | 71/99 [00:01<00:00, 51.03it/s]

eigen seeded symmetric sparse smooth r32 sim=0.8020:  72%|███████▏  | 71/99 [00:01<00:00, 51.03it/s]

eigen seeded symmetric sparse smooth r32 sim=0.8020:  78%|███████▊  | 77/99 [00:01<00:00, 51.82it/s]

eigen seeded symmetric sparse smooth r32 sim=0.8020:  78%|███████▊  | 77/99 [00:01<00:00, 51.82it/s]

eigen seeded symmetric sparse smooth r32 sim=0.8021:  78%|███████▊  | 77/99 [00:01<00:00, 51.82it/s]

eigen seeded symmetric sparse smooth r32 sim=0.8022:  78%|███████▊  | 77/99 [00:01<00:00, 51.82it/s]

eigen seeded symmetric sparse smooth r32 sim=0.8022:  78%|███████▊  | 77/99 [00:01<00:00, 51.82it/s]

eigen seeded symmetric sparse smooth r32 sim=0.8023:  78%|███████▊  | 77/99 [00:01<00:00, 51.82it/s]

eigen seeded symmetric sparse smooth r32 sim=0.8023:  78%|███████▊  | 77/99 [00:01<00:00, 51.82it/s]

eigen seeded symmetric sparse smooth r32 sim=0.8023:  84%|████████▍ | 83/99 [00:01<00:00, 49.34it/s]

eigen seeded symmetric sparse smooth r32 sim=0.8023:  84%|████████▍ | 83/99 [00:01<00:00, 49.34it/s]

eigen seeded symmetric sparse smooth r32 sim=0.8024:  84%|████████▍ | 83/99 [00:01<00:00, 49.34it/s]

eigen seeded symmetric sparse smooth r32 sim=0.8024:  84%|████████▍ | 83/99 [00:01<00:00, 49.34it/s]

eigen seeded symmetric sparse smooth r32 sim=0.8024:  84%|████████▍ | 83/99 [00:01<00:00, 49.34it/s]

eigen seeded symmetric sparse smooth r32 sim=0.8024:  84%|████████▍ | 83/99 [00:01<00:00, 49.34it/s]

eigen seeded symmetric sparse smooth r32 sim=0.8024:  89%|████████▉ | 88/99 [00:01<00:00, 48.46it/s]

eigen seeded symmetric sparse smooth r32 sim=0.8025:  89%|████████▉ | 88/99 [00:01<00:00, 48.46it/s]

eigen seeded symmetric sparse smooth r32 sim=0.8025:  89%|████████▉ | 88/99 [00:01<00:00, 48.46it/s]

eigen seeded symmetric sparse smooth r32 sim=0.8025:  89%|████████▉ | 88/99 [00:01<00:00, 48.46it/s]

eigen seeded symmetric sparse smooth r32 sim=0.8025:  89%|████████▉ | 88/99 [00:01<00:00, 48.46it/s]

eigen seeded symmetric sparse smooth r32 sim=0.8025:  89%|████████▉ | 88/99 [00:01<00:00, 48.46it/s]

eigen seeded symmetric sparse smooth r32 sim=0.8025:  89%|████████▉ | 88/99 [00:01<00:00, 48.46it/s]

eigen seeded symmetric sparse smooth r32 sim=0.8025:  95%|█████████▍| 94/99 [00:01<00:00, 50.12it/s]

eigen seeded symmetric sparse smooth r32 sim=0.8025:  95%|█████████▍| 94/99 [00:01<00:00, 50.12it/s]

eigen seeded symmetric sparse smooth r32 sim=0.8025:  95%|█████████▍| 94/99 [00:01<00:00, 50.12it/s]

eigen seeded symmetric sparse smooth r32 sim=0.8025:  95%|█████████▍| 94/99 [00:01<00:00, 50.12it/s]

eigen seeded symmetric sparse smooth r32 sim=0.8025:  95%|█████████▍| 94/99 [00:01<00:00, 50.12it/s]

eigen seeded symmetric sparse smooth r32 sim=0.8025:  95%|█████████▍| 94/99 [00:01<00:00, 50.12it/s]

eigen seeded symmetric sparse smooth r32 sim=0.8025: 100%|██████████| 99/99 [00:01<00:00, 49.92it/s]

,name,similarity,test_acc,pattern_gini,locality_7x7,class_selectivity,top_sigma_frac
5,evidence split sparse smooth r32,0.877034,0.9548,0.440257,0.254946,0.120680,0.306341
4,evidence split r32,0.872256,0.9611,0.434809,0.237860,0.109408,0.290891
1,cp r32 symmetry-soft,0.860983,0.9511,0.437123,0.238074,0.103718,0.299290
0,provided Sparse r32,0.858908,0.9492,0.440377,0.264228,0.106274,0.295426
7,eigen seeded symmetric sparse smooth r32,0.802525,0.9265,0.223442,0.151670,0.117094,0.290446
3,symmetric sparse smooth r32,0.787751,0.9316,0.222727,0.138692,0.108916,0.300652
2,symmetric r32,0.778788,0.8867,0.221623,0.139064,0.116112,0.287478
6,nonnegative strokes r48,0.087126,0.4322,0.010952,0.063500,0.103726,0.277420

## Pick A Best Candidate

In [16]:
# The default ranking weights faithfulness and accuracy first, then interpretability proxies.
def score_row(row):
    return (
        4.0 * row["similarity"]
        + 4.0 * row["test_acc"]
        + 0.8 * row["pattern_gini"]
        + 0.8 * row["locality_7x7"]
        + 0.8 * row["class_selectivity"]
    )

ranked = sorted(rows, key=score_row, reverse=True)
best_name = next(row["name"] for row in ranked if row["name"] in trained and not row["name"].startswith("provided Sparse"))
best = trained[best_name]
best_name, ranked[:3]

('evidence split sparse smooth r32',
 [{'name': 'evidence split sparse smooth r32',
   'similarity': 0.8770343065261841,
   'test_acc': 0.9547999501228333,
   'pattern_gini': 0.4402574598789215,
   'locality_7x7': 0.25494641065597534,
   'class_selectivity': 0.12067985534667969,
   'top_sigma_frac': 0.3063405156135559},
  {'name': 'evidence split r32',
   'similarity': 0.8722564578056335,
   'test_acc': 0.9610999822616577,
   'pattern_gini': 0.43480879068374634,
   'locality_7x7': 0.23786047101020813,
   'class_selectivity': 0.10940754413604736,
   'top_sigma_frac': 0.29089149832725525},
  {'name': 'provided Sparse r32',
   'similarity': 0.8589080572128296,
   'test_acc': 0.9491999745368958,
   'pattern_gini': 0.44037699699401855,
   'locality_7x7': 0.2642282247543335,
   'class_selectivity': 0.10627377033233643,
   'top_sigma_frac': 0.29542607069015503}])

In [17]:
plus, minus, down, sigma = best.decompose()
best_fig = component_figure(plus, minus, down, sigma, k=16, title=f"BEST: {best_name}")
save_fig(best_fig, "components_best_decomposition")
plot_sigma(sigma, f"BEST {best_name}")

## Faithfulness: Keep-Only And Ablation Curves

In [18]:
@torch.no_grad()
def faithfulness_curves(factor_model, name, ks=(1, 2, 4, 8, 16, 24, 32, 48, 64), alias=None):
    sigma = component_strengths(factor_model)
    rank = sigma.numel()
    order = sigma.argsort(descending=True)
    rows = []
    for k in ks:
        k = min(k, rank)
        keep = torch.zeros(rank, device=device)
        keep[order[:k]] = 1
        drop = torch.ones(rank, device=device)
        drop[order[:k]] = 0
        keep_logits = factor_model(test.x, mask=keep)
        drop_logits = factor_model(test.x, mask=drop)
        rows.append({
            "k": k,
            "mode": "keep top-k",
            "acc": (keep_logits.argmax(-1) == test.y).float().mean().item(),
        })
        rows.append({
            "k": k,
            "mode": "drop top-k",
            "acc": (drop_logits.argmax(-1) == test.y).float().mean().item(),
        })
    if pd is not None:
        df = pd.DataFrame(rows)
        fig = px.line(df, x="k", y="acc", color="mode", markers=True, template="plotly_white", title=f"Faithfulness curves: {name}")
    else:
        fig = px.line(rows, x="k", y="acc", color="mode", markers=True, template="plotly_white", title=f"Faithfulness curves: {name}")
    save_fig(fig, f"faithfulness_{name.replace(' ', '_').lower()}")
    if alias is not None:
        save_fig(fig, alias)
    return rows

faithfulness = faithfulness_curves(best, best_name, alias="faithfulness_best_decomposition")
show_table(faithfulness)

     k        mode     acc
0    1  keep top-k  0.1863
1    1  drop top-k  0.9393
2    2  keep top-k  0.2231
3    2  drop top-k  0.9322
4    4  keep top-k  0.2723
5    4  drop top-k  0.9251
6    8  keep top-k  0.4145
7    8  drop top-k  0.8863
8   16  keep top-k  0.6761
9   16  drop top-k  0.5990
10  24  keep top-k  0.8676
11  24  drop top-k  0.4555
12  32  keep top-k  0.9548
13  32  drop top-k  0.0980
14  32  keep top-k  0.9548
15  32  drop top-k  0.0980
16  32  keep top-k  0.9548
17  32  drop top-k  0.0980

     k        mode     acc
0    1  keep top-k  0.1863
1    1  drop top-k  0.9393
2    2  keep top-k  0.2231
3    2  drop top-k  0.9322
4    4  keep top-k  0.2723
5    4  drop top-k  0.9251
6    8  keep top-k  0.4145
7    8  drop top-k  0.8863
8   16  keep top-k  0.6761
9   16  drop top-k  0.5990
10  24  keep top-k  0.8676
11  24  drop top-k  0.4555
12  32  keep top-k  0.9548
13  32  drop top-k  0.0980
14  32  keep top-k  0.9548
15  32  drop top-k  0.0980
16  32  keep top-k  0.9548
17  32  drop top-k  0.0980

## Activation Galleries

In [19]:
@torch.no_grad()
def activation_gallery(factor_model, name, component_indices=None, topn=8, alias=None):
    plus, minus, down, sigma = factor_model.decompose()
    order = component_strengths(factor_model).argsort(descending=True)
    if component_indices is None:
        component_indices = list(range(min(6, sigma.numel())))
    acts = factor_model.component_activations(train.x)[:, order]
    fig = make_subplots(
        rows=len(component_indices),
        cols=topn + 2,
        column_titles=["pos", "neg"] + [f"ex {i+1}" for i in range(topn)],
        vertical_spacing=0.03,
        horizontal_spacing=0.01,
    )
    for row, comp in enumerate(component_indices, start=1):
        fig.add_heatmap(z=plus[:, comp].detach().cpu().view(28, 28).flip(0), colorscale="RdBu", zmid=0, showscale=False, row=row, col=1)
        fig.add_heatmap(z=minus[:, comp].detach().cpu().view(28, 28).flip(0), colorscale="RdBu", zmid=0, showscale=False, row=row, col=2)
        top = acts[:, comp].abs().topk(topn).indices
        for j, idx in enumerate(top.tolist(), start=3):
            fig.add_heatmap(z=train.x[idx].detach().cpu().view(28, 28).flip(0), colorscale="gray", showscale=False, row=row, col=j)
    fig.update_xaxes(visible=False).update_yaxes(visible=False)
    fig.update_layout(
        width=125 * (topn + 2),
        height=115 * len(component_indices),
        title=f"Activation galleries: {name}",
        template="plotly_white",
        margin=dict(l=5, r=5, t=45, b=5),
    )
    return save_fig(fig, f"activation_gallery_{name.replace(' ', '_').lower()}")

activation_gallery(best, best_name, topn=8)

## Seed Stability / Consensus

In [20]:
def top_patterns_for_matching(factor_model, k=16):
    plus, minus, down, sigma = factor_model.decompose()
    patterns = torch.cat([plus[:, :k], minus[:, :k]], dim=1)
    return normalize_columns(patterns)


@torch.no_grad()
def greedy_match_score(reference, candidate):
    sim = (reference.T @ candidate).abs().detach().cpu()
    used_ref, used_cand, vals = set(), set(), []
    flat_order = sim.flatten().argsort(descending=True).tolist()
    n_ref, n_cand = sim.shape
    for flat in flat_order:
        i, j = divmod(flat, n_cand)
        if i in used_ref or j in used_cand:
            continue
        used_ref.add(i)
        used_cand.add(j)
        vals.append(float(sim[i, j]))
        if len(vals) == min(n_ref, n_cand):
            break
    return sum(vals) / max(1, len(vals)), vals


def consensus_run(factory, reg, name, seeds=(11, 12, 13), steps=300, lr=0.035, k=16):
    models = []
    rows = []
    for seed in seeds:
        set_seed(seed)
        m, hist = fit_factor_model(factory(), f"{name} seed {seed}", steps=steps, lr=lr, reg=reg, seed=None, progress=True)
        models.append(m)
        rows.append(metric_dict(f"{name} seed {seed}", m))
    ref = top_patterns_for_matching(models[0], k=k)
    for seed, m, row in zip(seeds[1:], models[1:], rows[1:]):
        score, vals = greedy_match_score(ref, top_patterns_for_matching(m, k=k))
        row["consensus_vs_seed0"] = score
    rows[0]["consensus_vs_seed0"] = 1.0
    return models, rows

# Run this on the best-looking family. Reduce steps if iterating quickly.
consensus_models, consensus_rows = consensus_run(
    factory=lambda: EvidenceSplitModel(rank=BASE_RANK),
    reg=RegConfig(l1=2e-4, tv=2e-3, d_l1=2e-4, duplicate=1e-3),
    name="evidence split sparse smooth consensus",
    seeds=(11, 12, 13),
    steps=CONSENSUS_STEPS,
    lr=0.035,
    k=12,
)
show_table(consensus_rows)
plot_factor_components(consensus_models[0], "consensus reference evidence split sparse smooth", k=12)

evidence split sparse smooth consensus seed 11:   0%|          | 0/80 [00:00<?, ?it/s]

evidence split sparse smooth consensus seed 11 sim=-0.0006:   0%|          | 0/80 [00:00<?, ?it/s]

evidence split sparse smooth consensus seed 11 sim=0.0549:   0%|          | 0/80 [00:00<?, ?it/s]

evidence split sparse smooth consensus seed 11 sim=0.3119:   0%|          | 0/80 [00:00<?, ?it/s]

evidence split sparse smooth consensus seed 11 sim=0.3119:   4%|▍         | 3/80 [00:00<00:02, 28.53it/s]

evidence split sparse smooth consensus seed 11 sim=0.4818:   4%|▍         | 3/80 [00:00<00:02, 28.53it/s]

evidence split sparse smooth consensus seed 11 sim=0.5787:   4%|▍         | 3/80 [00:00<00:02, 28.53it/s]

evidence split sparse smooth consensus seed 11 sim=0.6367:   4%|▍         | 3/80 [00:00<00:02, 28.53it/s]

evidence split sparse smooth consensus seed 11 sim=0.6734:   4%|▍         | 3/80 [00:00<00:02, 28.53it/s]

evidence split sparse smooth consensus seed 11 sim=0.6986:   4%|▍         | 3/80 [00:00<00:02, 28.53it/s]

evidence split sparse smooth consensus seed 11 sim=0.7175:   4%|▍         | 3/80 [00:00<00:02, 28.53it/s]

evidence split sparse smooth consensus seed 11 sim=0.7175:  11%|█▏        | 9/80 [00:00<00:01, 43.25it/s]

evidence split sparse smooth consensus seed 11 sim=0.7326:  11%|█▏        | 9/80 [00:00<00:01, 43.25it/s]

evidence split sparse smooth consensus seed 11 sim=0.7452:  11%|█▏        | 9/80 [00:00<00:01, 43.25it/s]

evidence split sparse smooth consensus seed 11 sim=0.7560:  11%|█▏        | 9/80 [00:00<00:01, 43.25it/s]

evidence split sparse smooth consensus seed 11 sim=0.7657:  11%|█▏        | 9/80 [00:00<00:01, 43.25it/s]

evidence split sparse smooth consensus seed 11 sim=0.7743:  11%|█▏        | 9/80 [00:00<00:01, 43.25it/s]

evidence split sparse smooth consensus seed 11 sim=0.7743:  18%|█▊        | 14/80 [00:00<00:01, 45.63it/s]

evidence split sparse smooth consensus seed 11 sim=0.7820:  18%|█▊        | 14/80 [00:00<00:01, 45.63it/s]

evidence split sparse smooth consensus seed 11 sim=0.7889:  18%|█▊        | 14/80 [00:00<00:01, 45.63it/s]

evidence split sparse smooth consensus seed 11 sim=0.7949:  18%|█▊        | 14/80 [00:00<00:01, 45.63it/s]

evidence split sparse smooth consensus seed 11 sim=0.8002:  18%|█▊        | 14/80 [00:00<00:01, 45.63it/s]

evidence split sparse smooth consensus seed 11 sim=0.8049:  18%|█▊        | 14/80 [00:00<00:01, 45.63it/s]

evidence split sparse smooth consensus seed 11 sim=0.8049:  24%|██▍       | 19/80 [00:00<00:01, 46.91it/s]

evidence split sparse smooth consensus seed 11 sim=0.8091:  24%|██▍       | 19/80 [00:00<00:01, 46.91it/s]

evidence split sparse smooth consensus seed 11 sim=0.8130:  24%|██▍       | 19/80 [00:00<00:01, 46.91it/s]

evidence split sparse smooth consensus seed 11 sim=0.8164:  24%|██▍       | 19/80 [00:00<00:01, 46.91it/s]

evidence split sparse smooth consensus seed 11 sim=0.8197:  24%|██▍       | 19/80 [00:00<00:01, 46.91it/s]

evidence split sparse smooth consensus seed 11 sim=0.8226:  24%|██▍       | 19/80 [00:00<00:01, 46.91it/s]

evidence split sparse smooth consensus seed 11 sim=0.8226:  30%|███       | 24/80 [00:00<00:01, 45.05it/s]

evidence split sparse smooth consensus seed 11 sim=0.8254:  30%|███       | 24/80 [00:00<00:01, 45.05it/s]

evidence split sparse smooth consensus seed 11 sim=0.8279:  30%|███       | 24/80 [00:00<00:01, 45.05it/s]

evidence split sparse smooth consensus seed 11 sim=0.8302:  30%|███       | 24/80 [00:00<00:01, 45.05it/s]

evidence split sparse smooth consensus seed 11 sim=0.8324:  30%|███       | 24/80 [00:00<00:01, 45.05it/s]

evidence split sparse smooth consensus seed 11 sim=0.8343:  30%|███       | 24/80 [00:00<00:01, 45.05it/s]

evidence split sparse smooth consensus seed 11 sim=0.8343:  36%|███▋      | 29/80 [00:00<00:01, 40.56it/s]

evidence split sparse smooth consensus seed 11 sim=0.8361:  36%|███▋      | 29/80 [00:00<00:01, 40.56it/s]

evidence split sparse smooth consensus seed 11 sim=0.8378:  36%|███▋      | 29/80 [00:00<00:01, 40.56it/s]

evidence split sparse smooth consensus seed 11 sim=0.8394:  36%|███▋      | 29/80 [00:00<00:01, 40.56it/s]

evidence split sparse smooth consensus seed 11 sim=0.8409:  36%|███▋      | 29/80 [00:00<00:01, 40.56it/s]

evidence split sparse smooth consensus seed 11 sim=0.8422:  36%|███▋      | 29/80 [00:00<00:01, 40.56it/s]

evidence split sparse smooth consensus seed 11 sim=0.8422:  42%|████▎     | 34/80 [00:00<00:01, 40.46it/s]

evidence split sparse smooth consensus seed 11 sim=0.8435:  42%|████▎     | 34/80 [00:00<00:01, 40.46it/s]

evidence split sparse smooth consensus seed 11 sim=0.8447:  42%|████▎     | 34/80 [00:00<00:01, 40.46it/s]

evidence split sparse smooth consensus seed 11 sim=0.8458:  42%|████▎     | 34/80 [00:00<00:01, 40.46it/s]

evidence split sparse smooth consensus seed 11 sim=0.8469:  42%|████▎     | 34/80 [00:00<00:01, 40.46it/s]

evidence split sparse smooth consensus seed 11 sim=0.8478:  42%|████▎     | 34/80 [00:00<00:01, 40.46it/s]

evidence split sparse smooth consensus seed 11 sim=0.8478:  49%|████▉     | 39/80 [00:00<00:01, 39.51it/s]

evidence split sparse smooth consensus seed 11 sim=0.8487:  49%|████▉     | 39/80 [00:00<00:01, 39.51it/s]

evidence split sparse smooth consensus seed 11 sim=0.8496:  49%|████▉     | 39/80 [00:01<00:01, 39.51it/s]

evidence split sparse smooth consensus seed 11 sim=0.8504:  49%|████▉     | 39/80 [00:01<00:01, 39.51it/s]

evidence split sparse smooth consensus seed 11 sim=0.8511:  49%|████▉     | 39/80 [00:01<00:01, 39.51it/s]

evidence split sparse smooth consensus seed 11 sim=0.8511:  54%|█████▍    | 43/80 [00:01<00:00, 39.41it/s]

evidence split sparse smooth consensus seed 11 sim=0.8518:  54%|█████▍    | 43/80 [00:01<00:00, 39.41it/s]

evidence split sparse smooth consensus seed 11 sim=0.8525:  54%|█████▍    | 43/80 [00:01<00:00, 39.41it/s]

evidence split sparse smooth consensus seed 11 sim=0.8531:  54%|█████▍    | 43/80 [00:01<00:00, 39.41it/s]

evidence split sparse smooth consensus seed 11 sim=0.8537:  54%|█████▍    | 43/80 [00:01<00:00, 39.41it/s]

evidence split sparse smooth consensus seed 11 sim=0.8542:  54%|█████▍    | 43/80 [00:01<00:00, 39.41it/s]

evidence split sparse smooth consensus seed 11 sim=0.8542:  60%|██████    | 48/80 [00:01<00:00, 40.41it/s]

evidence split sparse smooth consensus seed 11 sim=0.8547:  60%|██████    | 48/80 [00:01<00:00, 40.41it/s]

evidence split sparse smooth consensus seed 11 sim=0.8552:  60%|██████    | 48/80 [00:01<00:00, 40.41it/s]

evidence split sparse smooth consensus seed 11 sim=0.8556:  60%|██████    | 48/80 [00:01<00:00, 40.41it/s]

evidence split sparse smooth consensus seed 11 sim=0.8561:  60%|██████    | 48/80 [00:01<00:00, 40.41it/s]

evidence split sparse smooth consensus seed 11 sim=0.8564:  60%|██████    | 48/80 [00:01<00:00, 40.41it/s]

evidence split sparse smooth consensus seed 11 sim=0.8564:  66%|██████▋   | 53/80 [00:01<00:00, 42.93it/s]

evidence split sparse smooth consensus seed 11 sim=0.8568:  66%|██████▋   | 53/80 [00:01<00:00, 42.93it/s]

evidence split sparse smooth consensus seed 11 sim=0.8571:  66%|██████▋   | 53/80 [00:01<00:00, 42.93it/s]

evidence split sparse smooth consensus seed 11 sim=0.8574:  66%|██████▋   | 53/80 [00:01<00:00, 42.93it/s]

evidence split sparse smooth consensus seed 11 sim=0.8577:  66%|██████▋   | 53/80 [00:01<00:00, 42.93it/s]

evidence split sparse smooth consensus seed 11 sim=0.8580:  66%|██████▋   | 53/80 [00:01<00:00, 42.93it/s]

evidence split sparse smooth consensus seed 11 sim=0.8580:  72%|███████▎  | 58/80 [00:01<00:00, 42.72it/s]

evidence split sparse smooth consensus seed 11 sim=0.8582:  72%|███████▎  | 58/80 [00:01<00:00, 42.72it/s]

evidence split sparse smooth consensus seed 11 sim=0.8584:  72%|███████▎  | 58/80 [00:01<00:00, 42.72it/s]

evidence split sparse smooth consensus seed 11 sim=0.8586:  72%|███████▎  | 58/80 [00:01<00:00, 42.72it/s]

evidence split sparse smooth consensus seed 11 sim=0.8588:  72%|███████▎  | 58/80 [00:01<00:00, 42.72it/s]

evidence split sparse smooth consensus seed 11 sim=0.8590:  72%|███████▎  | 58/80 [00:01<00:00, 42.72it/s]

evidence split sparse smooth consensus seed 11 sim=0.8590:  79%|███████▉  | 63/80 [00:01<00:00, 43.70it/s]

evidence split sparse smooth consensus seed 11 sim=0.8591:  79%|███████▉  | 63/80 [00:01<00:00, 43.70it/s]

evidence split sparse smooth consensus seed 11 sim=0.8592:  79%|███████▉  | 63/80 [00:01<00:00, 43.70it/s]

evidence split sparse smooth consensus seed 11 sim=0.8593:  79%|███████▉  | 63/80 [00:01<00:00, 43.70it/s]

evidence split sparse smooth consensus seed 11 sim=0.8594:  79%|███████▉  | 63/80 [00:01<00:00, 43.70it/s]

evidence split sparse smooth consensus seed 11 sim=0.8595:  79%|███████▉  | 63/80 [00:01<00:00, 43.70it/s]

evidence split sparse smooth consensus seed 11 sim=0.8595:  85%|████████▌ | 68/80 [00:01<00:00, 43.47it/s]

evidence split sparse smooth consensus seed 11 sim=0.8596:  85%|████████▌ | 68/80 [00:01<00:00, 43.47it/s]

evidence split sparse smooth consensus seed 11 sim=0.8597:  85%|████████▌ | 68/80 [00:01<00:00, 43.47it/s]

evidence split sparse smooth consensus seed 11 sim=0.8597:  85%|████████▌ | 68/80 [00:01<00:00, 43.47it/s]

evidence split sparse smooth consensus seed 11 sim=0.8598:  85%|████████▌ | 68/80 [00:01<00:00, 43.47it/s]

evidence split sparse smooth consensus seed 11 sim=0.8598:  85%|████████▌ | 68/80 [00:01<00:00, 43.47it/s]

evidence split sparse smooth consensus seed 11 sim=0.8598:  91%|█████████▏| 73/80 [00:01<00:00, 42.73it/s]

evidence split sparse smooth consensus seed 11 sim=0.8599:  91%|█████████▏| 73/80 [00:01<00:00, 42.73it/s]

evidence split sparse smooth consensus seed 11 sim=0.8599:  91%|█████████▏| 73/80 [00:01<00:00, 42.73it/s]

evidence split sparse smooth consensus seed 11 sim=0.8599:  91%|█████████▏| 73/80 [00:01<00:00, 42.73it/s]

evidence split sparse smooth consensus seed 11 sim=0.8599:  91%|█████████▏| 73/80 [00:01<00:00, 42.73it/s]

evidence split sparse smooth consensus seed 11 sim=0.8599:  91%|█████████▏| 73/80 [00:01<00:00, 42.73it/s]

evidence split sparse smooth consensus seed 11 sim=0.8599:  98%|█████████▊| 78/80 [00:01<00:00, 40.64it/s]

evidence split sparse smooth consensus seed 11 sim=0.8599:  98%|█████████▊| 78/80 [00:01<00:00, 40.64it/s]

evidence split sparse smooth consensus seed 11 sim=0.8599:  98%|█████████▊| 78/80 [00:01<00:00, 40.64it/s]

evidence split sparse smooth consensus seed 11 sim=0.8599: 100%|██████████| 80/80 [00:01<00:00, 41.48it/s]

evidence split sparse smooth consensus seed 12:   0%|          | 0/80 [00:00<?, ?it/s]

evidence split sparse smooth consensus seed 12 sim=-0.0003:   0%|          | 0/80 [00:00<?, ?it/s]

evidence split sparse smooth consensus seed 12 sim=0.0555:   0%|          | 0/80 [00:00<?, ?it/s]

evidence split sparse smooth consensus seed 12 sim=0.3134:   0%|          | 0/80 [00:00<?, ?it/s]

evidence split sparse smooth consensus seed 12 sim=0.4826:   0%|          | 0/80 [00:00<?, ?it/s]

evidence split sparse smooth consensus seed 12 sim=0.4826:   5%|▌         | 4/80 [00:00<00:02, 35.32it/s]

evidence split sparse smooth consensus seed 12 sim=0.5813:   5%|▌         | 4/80 [00:00<00:02, 35.32it/s]

evidence split sparse smooth consensus seed 12 sim=0.6386:   5%|▌         | 4/80 [00:00<00:02, 35.32it/s]

evidence split sparse smooth consensus seed 12 sim=0.6761:   5%|▌         | 4/80 [00:00<00:02, 35.32it/s]

evidence split sparse smooth consensus seed 12 sim=0.7029:   5%|▌         | 4/80 [00:00<00:02, 35.32it/s]

evidence split sparse smooth consensus seed 12 sim=0.7230:   5%|▌         | 4/80 [00:00<00:02, 35.32it/s]

evidence split sparse smooth consensus seed 12 sim=0.7230:  11%|█▏        | 9/80 [00:00<00:01, 41.48it/s]

evidence split sparse smooth consensus seed 12 sim=0.7390:  11%|█▏        | 9/80 [00:00<00:01, 41.48it/s]

evidence split sparse smooth consensus seed 12 sim=0.7522:  11%|█▏        | 9/80 [00:00<00:01, 41.48it/s]

evidence split sparse smooth consensus seed 12 sim=0.7636:  11%|█▏        | 9/80 [00:00<00:01, 41.48it/s]

evidence split sparse smooth consensus seed 12 sim=0.7734:  11%|█▏        | 9/80 [00:00<00:01, 41.48it/s]

evidence split sparse smooth consensus seed 12 sim=0.7819:  11%|█▏        | 9/80 [00:00<00:01, 41.48it/s]

evidence split sparse smooth consensus seed 12 sim=0.7819:  18%|█▊        | 14/80 [00:00<00:01, 42.82it/s]

evidence split sparse smooth consensus seed 12 sim=0.7892:  18%|█▊        | 14/80 [00:00<00:01, 42.82it/s]

evidence split sparse smooth consensus seed 12 sim=0.7957:  18%|█▊        | 14/80 [00:00<00:01, 42.82it/s]

evidence split sparse smooth consensus seed 12 sim=0.8014:  18%|█▊        | 14/80 [00:00<00:01, 42.82it/s]

evidence split sparse smooth consensus seed 12 sim=0.8066:  18%|█▊        | 14/80 [00:00<00:01, 42.82it/s]

evidence split sparse smooth consensus seed 12 sim=0.8112:  18%|█▊        | 14/80 [00:00<00:01, 42.82it/s]

evidence split sparse smooth consensus seed 12 sim=0.8112:  24%|██▍       | 19/80 [00:00<00:01, 43.07it/s]

evidence split sparse smooth consensus seed 12 sim=0.8154:  24%|██▍       | 19/80 [00:00<00:01, 43.07it/s]

evidence split sparse smooth consensus seed 12 sim=0.8192:  24%|██▍       | 19/80 [00:00<00:01, 43.07it/s]

evidence split sparse smooth consensus seed 12 sim=0.8226:  24%|██▍       | 19/80 [00:00<00:01, 43.07it/s]

evidence split sparse smooth consensus seed 12 sim=0.8257:  24%|██▍       | 19/80 [00:00<00:01, 43.07it/s]

evidence split sparse smooth consensus seed 12 sim=0.8285:  24%|██▍       | 19/80 [00:00<00:01, 43.07it/s]

evidence split sparse smooth consensus seed 12 sim=0.8285:  30%|███       | 24/80 [00:00<00:01, 42.31it/s]

evidence split sparse smooth consensus seed 12 sim=0.8311:  30%|███       | 24/80 [00:00<00:01, 42.31it/s]

evidence split sparse smooth consensus seed 12 sim=0.8335:  30%|███       | 24/80 [00:00<00:01, 42.31it/s]

evidence split sparse smooth consensus seed 12 sim=0.8357:  30%|███       | 24/80 [00:00<00:01, 42.31it/s]

evidence split sparse smooth consensus seed 12 sim=0.8377:  30%|███       | 24/80 [00:00<00:01, 42.31it/s]

evidence split sparse smooth consensus seed 12 sim=0.8396:  30%|███       | 24/80 [00:00<00:01, 42.31it/s]

evidence split sparse smooth consensus seed 12 sim=0.8396:  36%|███▋      | 29/80 [00:00<00:01, 40.99it/s]

evidence split sparse smooth consensus seed 12 sim=0.8414:  36%|███▋      | 29/80 [00:00<00:01, 40.99it/s]

evidence split sparse smooth consensus seed 12 sim=0.8430:  36%|███▋      | 29/80 [00:00<00:01, 40.99it/s]

evidence split sparse smooth consensus seed 12 sim=0.8445:  36%|███▋      | 29/80 [00:00<00:01, 40.99it/s]

evidence split sparse smooth consensus seed 12 sim=0.8459:  36%|███▋      | 29/80 [00:00<00:01, 40.99it/s]

evidence split sparse smooth consensus seed 12 sim=0.8472:  36%|███▋      | 29/80 [00:00<00:01, 40.99it/s]

evidence split sparse smooth consensus seed 12 sim=0.8472:  42%|████▎     | 34/80 [00:00<00:01, 39.63it/s]

evidence split sparse smooth consensus seed 12 sim=0.8484:  42%|████▎     | 34/80 [00:00<00:01, 39.63it/s]

evidence split sparse smooth consensus seed 12 sim=0.8495:  42%|████▎     | 34/80 [00:00<00:01, 39.63it/s]

evidence split sparse smooth consensus seed 12 sim=0.8506:  42%|████▎     | 34/80 [00:00<00:01, 39.63it/s]

evidence split sparse smooth consensus seed 12 sim=0.8516:  42%|████▎     | 34/80 [00:00<00:01, 39.63it/s]

evidence split sparse smooth consensus seed 12 sim=0.8525:  42%|████▎     | 34/80 [00:00<00:01, 39.63it/s]

evidence split sparse smooth consensus seed 12 sim=0.8525:  49%|████▉     | 39/80 [00:00<00:00, 41.38it/s]

evidence split sparse smooth consensus seed 12 sim=0.8533:  49%|████▉     | 39/80 [00:00<00:00, 41.38it/s]

evidence split sparse smooth consensus seed 12 sim=0.8541:  49%|████▉     | 39/80 [00:00<00:00, 41.38it/s]

evidence split sparse smooth consensus seed 12 sim=0.8549:  49%|████▉     | 39/80 [00:01<00:00, 41.38it/s]

evidence split sparse smooth consensus seed 12 sim=0.8556:  49%|████▉     | 39/80 [00:01<00:00, 41.38it/s]

evidence split sparse smooth consensus seed 12 sim=0.8562:  49%|████▉     | 39/80 [00:01<00:00, 41.38it/s]

evidence split sparse smooth consensus seed 12 sim=0.8562:  55%|█████▌    | 44/80 [00:01<00:00, 41.84it/s]

evidence split sparse smooth consensus seed 12 sim=0.8568:  55%|█████▌    | 44/80 [00:01<00:00, 41.84it/s]

evidence split sparse smooth consensus seed 12 sim=0.8574:  55%|█████▌    | 44/80 [00:01<00:00, 41.84it/s]

evidence split sparse smooth consensus seed 12 sim=0.8579:  55%|█████▌    | 44/80 [00:01<00:00, 41.84it/s]

evidence split sparse smooth consensus seed 12 sim=0.8584:  55%|█████▌    | 44/80 [00:01<00:00, 41.84it/s]

evidence split sparse smooth consensus seed 12 sim=0.8589:  55%|█████▌    | 44/80 [00:01<00:00, 41.84it/s]

evidence split sparse smooth consensus seed 12 sim=0.8589:  61%|██████▏   | 49/80 [00:01<00:00, 42.45it/s]

evidence split sparse smooth consensus seed 12 sim=0.8593:  61%|██████▏   | 49/80 [00:01<00:00, 42.45it/s]

evidence split sparse smooth consensus seed 12 sim=0.8597:  61%|██████▏   | 49/80 [00:01<00:00, 42.45it/s]

evidence split sparse smooth consensus seed 12 sim=0.8600:  61%|██████▏   | 49/80 [00:01<00:00, 42.45it/s]

evidence split sparse smooth consensus seed 12 sim=0.8604:  61%|██████▏   | 49/80 [00:01<00:00, 42.45it/s]

evidence split sparse smooth consensus seed 12 sim=0.8607:  61%|██████▏   | 49/80 [00:01<00:00, 42.45it/s]

evidence split sparse smooth consensus seed 12 sim=0.8607:  68%|██████▊   | 54/80 [00:01<00:00, 42.91it/s]

evidence split sparse smooth consensus seed 12 sim=0.8610:  68%|██████▊   | 54/80 [00:01<00:00, 42.91it/s]

evidence split sparse smooth consensus seed 12 sim=0.8613:  68%|██████▊   | 54/80 [00:01<00:00, 42.91it/s]

evidence split sparse smooth consensus seed 12 sim=0.8615:  68%|██████▊   | 54/80 [00:01<00:00, 42.91it/s]

evidence split sparse smooth consensus seed 12 sim=0.8617:  68%|██████▊   | 54/80 [00:01<00:00, 42.91it/s]

evidence split sparse smooth consensus seed 12 sim=0.8620:  68%|██████▊   | 54/80 [00:01<00:00, 42.91it/s]

evidence split sparse smooth consensus seed 12 sim=0.8620:  74%|███████▍  | 59/80 [00:01<00:00, 43.08it/s]

evidence split sparse smooth consensus seed 12 sim=0.8621:  74%|███████▍  | 59/80 [00:01<00:00, 43.08it/s]

evidence split sparse smooth consensus seed 12 sim=0.8623:  74%|███████▍  | 59/80 [00:01<00:00, 43.08it/s]

evidence split sparse smooth consensus seed 12 sim=0.8625:  74%|███████▍  | 59/80 [00:01<00:00, 43.08it/s]

evidence split sparse smooth consensus seed 12 sim=0.8626:  74%|███████▍  | 59/80 [00:01<00:00, 43.08it/s]

evidence split sparse smooth consensus seed 12 sim=0.8627:  74%|███████▍  | 59/80 [00:01<00:00, 43.08it/s]

evidence split sparse smooth consensus seed 12 sim=0.8627:  80%|████████  | 64/80 [00:01<00:00, 43.08it/s]

evidence split sparse smooth consensus seed 12 sim=0.8629:  80%|████████  | 64/80 [00:01<00:00, 43.08it/s]

evidence split sparse smooth consensus seed 12 sim=0.8630:  80%|████████  | 64/80 [00:01<00:00, 43.08it/s]

evidence split sparse smooth consensus seed 12 sim=0.8631:  80%|████████  | 64/80 [00:01<00:00, 43.08it/s]

evidence split sparse smooth consensus seed 12 sim=0.8631:  80%|████████  | 64/80 [00:01<00:00, 43.08it/s]

evidence split sparse smooth consensus seed 12 sim=0.8632:  80%|████████  | 64/80 [00:01<00:00, 43.08it/s]

evidence split sparse smooth consensus seed 12 sim=0.8632:  86%|████████▋ | 69/80 [00:01<00:00, 42.64it/s]

evidence split sparse smooth consensus seed 12 sim=0.8633:  86%|████████▋ | 69/80 [00:01<00:00, 42.64it/s]

evidence split sparse smooth consensus seed 12 sim=0.8633:  86%|████████▋ | 69/80 [00:01<00:00, 42.64it/s]

evidence split sparse smooth consensus seed 12 sim=0.8633:  86%|████████▋ | 69/80 [00:01<00:00, 42.64it/s]

evidence split sparse smooth consensus seed 12 sim=0.8634:  86%|████████▋ | 69/80 [00:01<00:00, 42.64it/s]

evidence split sparse smooth consensus seed 12 sim=0.8634:  86%|████████▋ | 69/80 [00:01<00:00, 42.64it/s]

evidence split sparse smooth consensus seed 12 sim=0.8634:  92%|█████████▎| 74/80 [00:01<00:00, 40.80it/s]

evidence split sparse smooth consensus seed 12 sim=0.8634:  92%|█████████▎| 74/80 [00:01<00:00, 40.80it/s]

evidence split sparse smooth consensus seed 12 sim=0.8634:  92%|█████████▎| 74/80 [00:01<00:00, 40.80it/s]

evidence split sparse smooth consensus seed 12 sim=0.8635:  92%|█████████▎| 74/80 [00:01<00:00, 40.80it/s]

evidence split sparse smooth consensus seed 12 sim=0.8635:  92%|█████████▎| 74/80 [00:01<00:00, 40.80it/s]

evidence split sparse smooth consensus seed 12 sim=0.8635:  92%|█████████▎| 74/80 [00:01<00:00, 40.80it/s]

evidence split sparse smooth consensus seed 12 sim=0.8635:  99%|█████████▉| 79/80 [00:01<00:00, 37.59it/s]

evidence split sparse smooth consensus seed 12 sim=0.8635:  99%|█████████▉| 79/80 [00:01<00:00, 37.59it/s]

evidence split sparse smooth consensus seed 12 sim=0.8635: 100%|██████████| 80/80 [00:01<00:00, 40.74it/s]

evidence split sparse smooth consensus seed 13:   0%|          | 0/80 [00:00<?, ?it/s]

evidence split sparse smooth consensus seed 13 sim=-0.0004:   0%|          | 0/80 [00:00<?, ?it/s]

evidence split sparse smooth consensus seed 13 sim=0.0634:   0%|          | 0/80 [00:00<?, ?it/s]

evidence split sparse smooth consensus seed 13 sim=0.3244:   0%|          | 0/80 [00:00<?, ?it/s]

evidence split sparse smooth consensus seed 13 sim=0.4911:   0%|          | 0/80 [00:00<?, ?it/s]

evidence split sparse smooth consensus seed 13 sim=0.5843:   0%|          | 0/80 [00:00<?, ?it/s]

evidence split sparse smooth consensus seed 13 sim=0.5843:   6%|▋         | 5/80 [00:00<00:01, 42.93it/s]

evidence split sparse smooth consensus seed 13 sim=0.6402:   6%|▋         | 5/80 [00:00<00:01, 42.93it/s]

evidence split sparse smooth consensus seed 13 sim=0.6759:   6%|▋         | 5/80 [00:00<00:01, 42.93it/s]

evidence split sparse smooth consensus seed 13 sim=0.7009:   6%|▋         | 5/80 [00:00<00:01, 42.93it/s]

evidence split sparse smooth consensus seed 13 sim=0.7199:   6%|▋         | 5/80 [00:00<00:01, 42.93it/s]

evidence split sparse smooth consensus seed 13 sim=0.7352:   6%|▋         | 5/80 [00:00<00:01, 42.93it/s]

evidence split sparse smooth consensus seed 13 sim=0.7352:  12%|█▎        | 10/80 [00:00<00:01, 44.21it/s]

evidence split sparse smooth consensus seed 13 sim=0.7480:  12%|█▎        | 10/80 [00:00<00:01, 44.21it/s]

evidence split sparse smooth consensus seed 13 sim=0.7589:  12%|█▎        | 10/80 [00:00<00:01, 44.21it/s]

evidence split sparse smooth consensus seed 13 sim=0.7685:  12%|█▎        | 10/80 [00:00<00:01, 44.21it/s]

evidence split sparse smooth consensus seed 13 sim=0.7770:  12%|█▎        | 10/80 [00:00<00:01, 44.21it/s]

evidence split sparse smooth consensus seed 13 sim=0.7845:  12%|█▎        | 10/80 [00:00<00:01, 44.21it/s]

evidence split sparse smooth consensus seed 13 sim=0.7845:  19%|█▉        | 15/80 [00:00<00:01, 45.63it/s]

evidence split sparse smooth consensus seed 13 sim=0.7913:  19%|█▉        | 15/80 [00:00<00:01, 45.63it/s]

evidence split sparse smooth consensus seed 13 sim=0.7973:  19%|█▉        | 15/80 [00:00<00:01, 45.63it/s]

evidence split sparse smooth consensus seed 13 sim=0.8028:  19%|█▉        | 15/80 [00:00<00:01, 45.63it/s]

evidence split sparse smooth consensus seed 13 sim=0.8076:  19%|█▉        | 15/80 [00:00<00:01, 45.63it/s]

evidence split sparse smooth consensus seed 13 sim=0.8119:  19%|█▉        | 15/80 [00:00<00:01, 45.63it/s]

evidence split sparse smooth consensus seed 13 sim=0.8119:  25%|██▌       | 20/80 [00:00<00:01, 44.08it/s]

evidence split sparse smooth consensus seed 13 sim=0.8158:  25%|██▌       | 20/80 [00:00<00:01, 44.08it/s]

evidence split sparse smooth consensus seed 13 sim=0.8192:  25%|██▌       | 20/80 [00:00<00:01, 44.08it/s]

evidence split sparse smooth consensus seed 13 sim=0.8223:  25%|██▌       | 20/80 [00:00<00:01, 44.08it/s]

evidence split sparse smooth consensus seed 13 sim=0.8252:  25%|██▌       | 20/80 [00:00<00:01, 44.08it/s]

evidence split sparse smooth consensus seed 13 sim=0.8278:  25%|██▌       | 20/80 [00:00<00:01, 44.08it/s]

evidence split sparse smooth consensus seed 13 sim=0.8278:  31%|███▏      | 25/80 [00:00<00:01, 45.23it/s]

evidence split sparse smooth consensus seed 13 sim=0.8302:  31%|███▏      | 25/80 [00:00<00:01, 45.23it/s]

evidence split sparse smooth consensus seed 13 sim=0.8324:  31%|███▏      | 25/80 [00:00<00:01, 45.23it/s]

evidence split sparse smooth consensus seed 13 sim=0.8345:  31%|███▏      | 25/80 [00:00<00:01, 45.23it/s]

evidence split sparse smooth consensus seed 13 sim=0.8364:  31%|███▏      | 25/80 [00:00<00:01, 45.23it/s]

evidence split sparse smooth consensus seed 13 sim=0.8382:  31%|███▏      | 25/80 [00:00<00:01, 45.23it/s]

evidence split sparse smooth consensus seed 13 sim=0.8382:  38%|███▊      | 30/80 [00:00<00:01, 43.70it/s]

evidence split sparse smooth consensus seed 13 sim=0.8398:  38%|███▊      | 30/80 [00:00<00:01, 43.70it/s]

evidence split sparse smooth consensus seed 13 sim=0.8413:  38%|███▊      | 30/80 [00:00<00:01, 43.70it/s]

evidence split sparse smooth consensus seed 13 sim=0.8428:  38%|███▊      | 30/80 [00:00<00:01, 43.70it/s]

evidence split sparse smooth consensus seed 13 sim=0.8441:  38%|███▊      | 30/80 [00:00<00:01, 43.70it/s]

evidence split sparse smooth consensus seed 13 sim=0.8453:  38%|███▊      | 30/80 [00:00<00:01, 43.70it/s]

evidence split sparse smooth consensus seed 13 sim=0.8453:  44%|████▍     | 35/80 [00:00<00:01, 40.22it/s]

evidence split sparse smooth consensus seed 13 sim=0.8465:  44%|████▍     | 35/80 [00:00<00:01, 40.22it/s]

evidence split sparse smooth consensus seed 13 sim=0.8476:  44%|████▍     | 35/80 [00:00<00:01, 40.22it/s]

evidence split sparse smooth consensus seed 13 sim=0.8486:  44%|████▍     | 35/80 [00:00<00:01, 40.22it/s]

evidence split sparse smooth consensus seed 13 sim=0.8495:  44%|████▍     | 35/80 [00:00<00:01, 40.22it/s]

evidence split sparse smooth consensus seed 13 sim=0.8504:  44%|████▍     | 35/80 [00:00<00:01, 40.22it/s]

evidence split sparse smooth consensus seed 13 sim=0.8504:  50%|█████     | 40/80 [00:00<00:01, 38.92it/s]

evidence split sparse smooth consensus seed 13 sim=0.8512:  50%|█████     | 40/80 [00:00<00:01, 38.92it/s]

evidence split sparse smooth consensus seed 13 sim=0.8519:  50%|█████     | 40/80 [00:01<00:01, 38.92it/s]

evidence split sparse smooth consensus seed 13 sim=0.8526:  50%|█████     | 40/80 [00:01<00:01, 38.92it/s]

evidence split sparse smooth consensus seed 13 sim=0.8533:  50%|█████     | 40/80 [00:01<00:01, 38.92it/s]

evidence split sparse smooth consensus seed 13 sim=0.8539:  50%|█████     | 40/80 [00:01<00:01, 38.92it/s]

evidence split sparse smooth consensus seed 13 sim=0.8539:  56%|█████▋    | 45/80 [00:01<00:00, 41.07it/s]

evidence split sparse smooth consensus seed 13 sim=0.8545:  56%|█████▋    | 45/80 [00:01<00:00, 41.07it/s]

evidence split sparse smooth consensus seed 13 sim=0.8550:  56%|█████▋    | 45/80 [00:01<00:00, 41.07it/s]

evidence split sparse smooth consensus seed 13 sim=0.8555:  56%|█████▋    | 45/80 [00:01<00:00, 41.07it/s]

evidence split sparse smooth consensus seed 13 sim=0.8560:  56%|█████▋    | 45/80 [00:01<00:00, 41.07it/s]

evidence split sparse smooth consensus seed 13 sim=0.8564:  56%|█████▋    | 45/80 [00:01<00:00, 41.07it/s]

evidence split sparse smooth consensus seed 13 sim=0.8564:  62%|██████▎   | 50/80 [00:01<00:00, 41.76it/s]

evidence split sparse smooth consensus seed 13 sim=0.8568:  62%|██████▎   | 50/80 [00:01<00:00, 41.76it/s]

evidence split sparse smooth consensus seed 13 sim=0.8572:  62%|██████▎   | 50/80 [00:01<00:00, 41.76it/s]

evidence split sparse smooth consensus seed 13 sim=0.8575:  62%|██████▎   | 50/80 [00:01<00:00, 41.76it/s]

evidence split sparse smooth consensus seed 13 sim=0.8578:  62%|██████▎   | 50/80 [00:01<00:00, 41.76it/s]

evidence split sparse smooth consensus seed 13 sim=0.8581:  62%|██████▎   | 50/80 [00:01<00:00, 41.76it/s]

evidence split sparse smooth consensus seed 13 sim=0.8581:  69%|██████▉   | 55/80 [00:01<00:00, 42.17it/s]

evidence split sparse smooth consensus seed 13 sim=0.8584:  69%|██████▉   | 55/80 [00:01<00:00, 42.17it/s]

evidence split sparse smooth consensus seed 13 sim=0.8586:  69%|██████▉   | 55/80 [00:01<00:00, 42.17it/s]

evidence split sparse smooth consensus seed 13 sim=0.8589:  69%|██████▉   | 55/80 [00:01<00:00, 42.17it/s]

evidence split sparse smooth consensus seed 13 sim=0.8591:  69%|██████▉   | 55/80 [00:01<00:00, 42.17it/s]

evidence split sparse smooth consensus seed 13 sim=0.8593:  69%|██████▉   | 55/80 [00:01<00:00, 42.17it/s]

evidence split sparse smooth consensus seed 13 sim=0.8593:  75%|███████▌  | 60/80 [00:01<00:00, 40.90it/s]

evidence split sparse smooth consensus seed 13 sim=0.8594:  75%|███████▌  | 60/80 [00:01<00:00, 40.90it/s]

evidence split sparse smooth consensus seed 13 sim=0.8596:  75%|███████▌  | 60/80 [00:01<00:00, 40.90it/s]

evidence split sparse smooth consensus seed 13 sim=0.8597:  75%|███████▌  | 60/80 [00:01<00:00, 40.90it/s]

evidence split sparse smooth consensus seed 13 sim=0.8599:  75%|███████▌  | 60/80 [00:01<00:00, 40.90it/s]

evidence split sparse smooth consensus seed 13 sim=0.8600:  75%|███████▌  | 60/80 [00:01<00:00, 40.90it/s]

evidence split sparse smooth consensus seed 13 sim=0.8600:  81%|████████▏ | 65/80 [00:01<00:00, 39.42it/s]

evidence split sparse smooth consensus seed 13 sim=0.8601:  81%|████████▏ | 65/80 [00:01<00:00, 39.42it/s]

evidence split sparse smooth consensus seed 13 sim=0.8602:  81%|████████▏ | 65/80 [00:01<00:00, 39.42it/s]

evidence split sparse smooth consensus seed 13 sim=0.8602:  81%|████████▏ | 65/80 [00:01<00:00, 39.42it/s]

evidence split sparse smooth consensus seed 13 sim=0.8603:  81%|████████▏ | 65/80 [00:01<00:00, 39.42it/s]

evidence split sparse smooth consensus seed 13 sim=0.8604:  81%|████████▏ | 65/80 [00:01<00:00, 39.42it/s]

evidence split sparse smooth consensus seed 13 sim=0.8604:  88%|████████▊ | 70/80 [00:01<00:00, 40.22it/s]

evidence split sparse smooth consensus seed 13 sim=0.8604:  88%|████████▊ | 70/80 [00:01<00:00, 40.22it/s]

evidence split sparse smooth consensus seed 13 sim=0.8605:  88%|████████▊ | 70/80 [00:01<00:00, 40.22it/s]

evidence split sparse smooth consensus seed 13 sim=0.8605:  88%|████████▊ | 70/80 [00:01<00:00, 40.22it/s]

evidence split sparse smooth consensus seed 13 sim=0.8605:  88%|████████▊ | 70/80 [00:01<00:00, 40.22it/s]

evidence split sparse smooth consensus seed 13 sim=0.8605:  88%|████████▊ | 70/80 [00:01<00:00, 40.22it/s]

evidence split sparse smooth consensus seed 13 sim=0.8605:  94%|█████████▍| 75/80 [00:01<00:00, 41.65it/s]

evidence split sparse smooth consensus seed 13 sim=0.8606:  94%|█████████▍| 75/80 [00:01<00:00, 41.65it/s]

evidence split sparse smooth consensus seed 13 sim=0.8606:  94%|█████████▍| 75/80 [00:01<00:00, 41.65it/s]

evidence split sparse smooth consensus seed 13 sim=0.8606:  94%|█████████▍| 75/80 [00:01<00:00, 41.65it/s]

evidence split sparse smooth consensus seed 13 sim=0.8606:  94%|█████████▍| 75/80 [00:01<00:00, 41.65it/s]

evidence split sparse smooth consensus seed 13 sim=0.8606:  94%|█████████▍| 75/80 [00:01<00:00, 41.65it/s]

evidence split sparse smooth consensus seed 13 sim=0.8606: 100%|██████████| 80/80 [00:01<00:00, 41.84it/s]

evidence split sparse smooth consensus seed 13 sim=0.8606: 100%|██████████| 80/80 [00:01<00:00, 41.78it/s]

,name,similarity,test_acc,pattern_gini,locality_7x7,class_selectivity,top_sigma_frac,consensus_vs_seed0
0,evidence split sparse smooth consensus seed 11,0.859923,0.9399,0.433521,0.235469,0.113702,0.288248,1.000000
1,evidence split sparse smooth consensus seed 12,0.863464,0.9568,0.437121,0.245698,0.102267,0.281830,0.539269
2,evidence split sparse smooth consensus seed 13,0.860575,0.9536,0.435162,0.243239,0.100038,0.283096,0.540127

## Notes And Interpretation

Use this section after running the notebook. The intended claims to check are:

- Does the provided sparse baseline win reconstruction but lose visual clarity?
- Does forcing symmetry make components cleaner or merely underfit?
- Does total variation remove pixel-level artifacts without washing out digit strokes?
- Do class-sparse logits make components easier to name?
- Do evidence-split components make the positive/negative interpretation more honest?
- Are the best components stable across seeds, or are the nicest-looking examples optimizer artifacts?

A standout final answer should include both successes and failures. For example, it is totally acceptable if nonnegative strokes look beautiful but reconstruct worse; that is a real interpretability tradeoff.

In [21]:
# Final compact export table for the README.
if pd is not None:
    final_df = pd.DataFrame(rows).sort_values("similarity", ascending=False)
    final_df.to_csv("figures/decomposition_results.csv", index=False)
    display(final_df)
else:
    rows

,name,similarity,test_acc,pattern_gini,locality_7x7,class_selectivity,top_sigma_frac
5,evidence split sparse smooth r32,0.877034,0.9548,0.440257,0.254946,0.120680,0.306341
4,evidence split r32,0.872256,0.9611,0.434809,0.237860,0.109408,0.290891
1,cp r32 symmetry-soft,0.860983,0.9511,0.437123,0.238074,0.103718,0.299290
0,provided Sparse r32,0.858908,0.9492,0.440377,0.264228,0.106274,0.295426
7,eigen seeded symmetric sparse smooth r32,0.802525,0.9265,0.223442,0.151670,0.117094,0.290446
3,symmetric sparse smooth r32,0.787751,0.9316,0.222727,0.138692,0.108916,0.300652
2,symmetric r32,0.778788,0.8867,0.221623,0.139064,0.116112,0.287478
6,nonnegative strokes r48,0.087126,0.4322,0.010952,0.063500,0.103726,0.277420

## Provisional Conclusion Template

After running the notebook, replace this with the concrete result. A useful shape is:

> The plain CP-style sparse decomposition achieved the strongest raw reconstruction, but its top components mixed several digit strokes. The best sparse/smooth evidence-split or symmetric variant gave up a small amount of cosine similarity while producing more localized and class-selective components. Ablation curves showed that the top components were not merely decorative: keeping only the leading components preserved a meaningful fraction of accuracy, and dropping them damaged predictions. Seed consensus was the strictest test; components that survived it are the most credible candidates for real shared model features.